"""人类学学科论文支持：民族志方法、田野调查、物质文化分析、语言与谱系。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="anthropology",
    aliases=(
        "anthropology",
        "Anthropology",
        "人类学",
        "ethnography",
        "民族志",
        "fieldwork",
        "田野",
        "cultural anthropology",
        "文化人类学",
        "社会人类学",
        "sociolinguistics",
        "语言人类学",
    ),
    paper_types={
        "ethnography": (
            "abstract",
            "introduction",
            "field site and methods",
            "ethnographic present",
            "analysis",
            "reflexivity",
            "conclusion",
            "references",
        ),
        "research": (
            "abstract",
            "introduction",
            "theory",
            "methods",
            "findings",
            "discussion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "genealogy of concepts",
            "debates",
            "directions",
            "references",
        ),
        "case_study": (
            "abstract",
            "context",
            "case description",
            "analysis",
            "conclusion",
            "references",
        ),
    },
    citation_style="Chicago Author-Date 或 AAA style（美国人类学学会）",
    reporting_standards={
        "fieldwork": "田野时长、地点、语言能力与关系建立过程须披露",
        "ethics": "知情同意与匿名化处理（IRB/伦理审查）须说明",
        "positionality": "研究者立场（reflexivity）须声明",
        "data": "引文须给访谈编号或田野笔记日期；人物化名统一",
        "translation": "翻译策略（直译/意译）与本地语言术语保留说明",
        "language_data": "语言调查须记录方言点、发音人信息、录音编号",
    },
    conventions=(
        "民族志现在时叙述与引语穿插；thick description 示范",
        "本地术语用斜体并附注释；系谱图/地图给来源",
        "理论对话明确（如实体论/本体论转向、多物种民族志）",
        "避免东方主义式概括；内部差异呈现",
        "访谈对象首次出现给年龄段/职业/居住时长；化名统一",
    ),
    key_venues=(
        "American Anthropologist",
        "Current Anthropology",
        "American Ethnologist",
        "Journal of the Royal Anthropological Institute",
        "Cultural Anthropology",
        "Man and Society",
        "人类学学报",
    ),
    units_and_formulas_notes=(
        "无统计要求时以质性论证为主",
        "如含量化内容给样本与描述统计；网络分析给指标定义（中心度、密度）",
        "地图/系谱图须给比例尺、数据来源与制图方法",
        "语言表须符合国际标准化（如 ISO 639）编码",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "教案与教材", "译文", "报告", "数据集"),
    tools=("NVivo", "MAXQDA", "QDA Miner", "ATLAS.ti", "AnthroKey", "UCMP（芝加哥人类学博物馆馆藏）", "Ethnologue", "Glottolog", "WALS（语言结构世界地图集）", "R", "RStudio", "Python", "GeoPandas", "QGIS", "Zoom H5 田野录音机", "Olympus 手持录音", "Canon EOS 单反相机", "DJI Mavic 无人机", "Garmin eTrex 手持 GPS", "民族志摄像机（Sony Handycam）", "LaTeX", "Zotero"),
    category="法学",
    databases=("CNKI", "万方", "OpenAlex", "Crossref", "PubMed", "Web of Science", "PsycINFO", "Harvard Peabody 数据库"),
)
