"""Astronomy 学科论文支持：观测天文学体裁、IAU/AAS 引用样式与天文学记法注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="astronomy",
    aliases=(
        "astronomy",
        "Astronomy",
        "天文学",
        "观测天文学",
        "observational astronomy",
        "恒星天体物理",
        "stellar astrophysics",
        "变星",
        "variable stars",
    ),
    paper_types={
        "observational_study": (
            "abstract",
            "introduction",
            "observations（望远镜、仪器、时间、曝光、天气/透明度）",
            "data reduction（平场、平减、定标、测光、视差）",
            "results（光变、测光、变率）",
            "discussion（对比变星分类与已有数据）",
            "conclusion",
            "references",
        ),
        "theoretical": (
            "abstract",
            "introduction",
            "model and formalism",
            "analysis",
            "predictions",
            "conclusion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "historical context",
            "main developments",
            "outlook",
            "references",
        ),
    },
    citation_style="AAS 样式（apj 2021 修订版；作者-年份或编号，视期刊）",
    reporting_standards={
        "observations": "望远镜/仪器、观测时间、曝光、天空背景、气象条件须报告",
        "calibration": "定标星、平场/偏暗、光子噪声、系统误差须报告",
        "photometry": "测光系统、滤光片、恒星大气的透射率须报告",
        "uncertainty": "光子噪声、测光误差与系统误差分别报告；总不确定度用合成",
        "archival": "使用的档案数据须给出数据编号（如 SDSS DR17、Gaia DR3）与检索日期",
        "reproducibility": "代码、数据与脚本链接须给出（GitHub 或 Zenodo）；随机种子须报告",
    },
    conventions=(
        "天体名用 IAU 标准缩写（NGC、M、M87, M31, M101）；恒星名用 B/HDR/HD/HR",
        "位置用赤经 RA J2000.0 与赤纬 Dec J2000.0；坐标给出精度（arcsec 或 mas）",
        "光谱用 nm 或 Å；波长 λ 与频率 ν 分别用；光年 yr / 秒差距 pc",
        "光度用 L⊙；质量用 M⊙；角尺度用 arcmin / arcsec",
        "误差用上下标 ±；显著性用 σ（3σ、5σ）；中位数用 \tilde{x}",
        "光变曲线用折线图；测光散点用 2D 直方图或核密度等高线",
        "数据表列出天体名、坐标、星等、光谱型、距离；缺失字段标 N/A",
        "图表首次出现处编号；数据点标误差棒；图注含望远镜/仪器/曝光",
    ),
    key_venues=(
        "The Astrophysical Journal (ApJ)",
        "The Astrophysical Journal Letters (ApJL)",
        "The Astronomical Journal (AJ)",
        "Monthly Notices of the Royal Astronomical Society (MNRAS)",
        "Astronomy & Astrophysics (A&A)",
        "The Publications of the Astronomical Society of the Pacific (PASP)",
        "The Open Journal of Astronomical Instruments (OJAI)",
        "Annual Review of Astronomy and Astrophysics",
    ),
    units_and_formulas_notes=(
        "距离 pc / kpc / Mpc；角尺度 arcmin / arcsec / mas",
        "光度 L⊙；质量 M⊙；温度 K；星等 m 无量纲",
        "波长 nm 或 Å；频率 Hz；光谱型 OBAFGKM",
        "公式用 amsmath；H₀ 报告 h₇₀ = H₀ / 100 km·s⁻¹·Mpc⁻¹",
        "误差用上下标 ±；中位数用 \tilde{x}，上下界用 \u27e8x\u27e9 与下/上箭头",
        "观测/模拟对比须使用相同统计口径（星等/距离/光度范围）",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "教案与教材", "报告", "数据集"),
    tools=("Astropy", "IRAF", "SAOImage DS9", "Stellarium", "Celestia", "AstroArt", "Aladin Lite", "TOPCAT", "STILTS", "CHARIS (SED fitting)", "Sedna (SED fitting)", "CASA", "RadioAstronomy", "AIPS", "Astrometry.net", "PyVista", "Pyvo", "Astroquery", "Matplotlib", "NumPy", "SciPy", "pandas", "R", "Jupyter", "VLA", "ALMA", "MeerKAT", "ASKAP", "SKA", "VLT", "Keck", "Gemini", "HST", "JWST", "Chandra", "XMM-Newton", "Fermi-LAT", "Swift", "HEASOFT", "SDSS", "Galaxy Zoo", "Gaia Archive", "SIMBAD", "VizieR", "Zotero", "EndNote"),
    category="理学",
    databases=("arXiv", "OpenAlex", "Crossref", "NASA ADS", "SIMBAD", "VizieR", "SDSS", "Gaia Archive", "CDS"),
)
