"""自动化 (Automation) 学科论文支持：控制理论、机器人、过程自动化、智能工厂。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="automation",
    aliases=(
        "Automation", "自动化", "自动控制",
        "control theory", "control systems", "控制理论与控制工程",
        "过程自动化", "process automation",
        "工业机器人", "industrial robotics",
        "智能控制", "intelligent control",
        "机器视觉", "machine vision",
        "SCADA", "DCS", "PLC",
        "smart manufacturing", "智能制造", "industrial IoT",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "system modeling",
            "controller design",
            "simulation / experiment",
            "results and analysis",
            "conclusions",
            "references",
        ),
        "case_study": (
            "abstract",
            "plant overview",
            "control architecture",
            "tuning process",
            "performance evaluation",
            "conclusions",
        ),
        "review": (
            "abstract",
            "historical overview",
            "current methods",
            "open challenges",
            "references",
        ),
    },
    citation_style="IEEE 样式（编号，工程惯例）",
    reporting_standards={
        "plant_model": "过程模型须声明阶次、传递函数或状态空间",
        "controller": "控制器类型（PID/MPC/RL/L1）与增益须完整报告",
        "experiment": "实验环境（温度、电压、传感器精度）须披露",
        "metrics": "性能指标（超调、稳态误差、上升时间、带宽）须报告",
        "safety": "涉及安全仪表系统的须遵循 IEC 61511 / SIL 等级",
        "standards": "引用标准须标注 IEC / ISA / GB 编号",
    },
    conventions=(
        "遵循 IEC 61131-3 PLC 编程标准（LD/FB/ST/SFC/IL）",
        "安全标准按 IEC 61511 / IEC 62061 定级（SIL 0-3）",
        "控制器参数遵循 ISA 参数标注（Kp/Ti/Td）",
        "信号命名遵循 ISA 仪表回路号规范",
        "运动控制遵循 IEC 61800 / IEC 62191 标准",
        "仿真验证须在硬件部署前完成",
        "实验数据须含时间序列与初始条件",
    ),
    key_venues=(
        "Automatica",
        "IEEE Transactions on Automatic Control",
        "IEEE Transactions on Industrial Electronics",
        "IEEE Transactions on Control Systems Technology",
        "IFAC Papers on Line",
        "Control Engineering Practice",
        "Annual Reviews in Control",
        "机器人技术与应用",
        "自动化学报",
        "控制理论与应用",
        "控制工程",
        "IEEE Transactions on Cybernetics",
        "IEEE Transactions on Neural Networks",
        "IEEE Robotics and Automation Letters",
        "IEEE Transactions on Robotics",
        "Mechatronics",
        "Robotics and Autonomous Systems",
        "Machine Vision and Applications",
    ),
    units_and_formulas_notes=(
        "时间 s/ms；频率 Hz 或 rad/s；角度 rad 或 °",
        "控制增益无量纲或 Kp/Ti/Td 单位分别 s",
        "温度 °C 或 K；压力 kPa；流量 m³/h",
        "电机功率 kW；电压 V；电流 A",
        "带宽 Hz；相位裕度 °；幅值裕度 dB",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "艺术作品", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("Siemens TIA Portal", "Siemens STEP 7", "Siemens WinCC", "Siemens S7-PLCSIM", "Siemens SINUMERIK", "Siemens SIMATIC S7-1500", "Rockwell Studio 5000", "Rockwell RSLogix", "Rockwell FactoryTalk", "Rockwell ControlLogix", "Allen-Bradley MicroLogix", "Allen-Bradley CompactLogix", "Beckhoff TwinCAT", "B&R Automation", "Wago", "Mitsubishi GX Works3", "Mitsubishi MELSEC", "Omron CX-Programmer", "Omron System Builder", "Keyence", "Schneider Unity Pro", "Schneider EcoStruxure", "CODESYS", "MATLAB Simulink", "ROS", "ROS 2", "Gazebo", "Python (NumPy/SciPy)", "OpenCV", "ROS Navigation Stack"),
    category="工学",
    databases=("arXiv", "OpenAlex", "Crossref", "IEEE Xplore", "CNKI", "Zenodo", "GitHub"),
)
