"""Aviation 学科论文支持：飞行器设计、飞行性能、航空安全与空管体裁、AIAA/ASA 引用样式。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="aviation",
    aliases=(
        "aviation",
        "航空",
        "航空工程",
        "飞行",
        "航空器",
        "航空运输",
        "飞行安全",
        "Aviation",
        "Aeronautics",
        "Flight Dynamics",
        "Air Transport",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "methods（建模、试验或仿真）",
            "results（性能、数据与验证）",
            "discussion（机理与工程意义）",
            "conclusion",
            "references",
        ),
        "safety_analysis": (
            "abstract",
            "introduction（问题与背景）",
            "data and methodology（数据来源与方法，含事件分类）",
            "results（安全事件统计与失效模式）",
            "discussion（根因分析与预防建议）",
            "conclusion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="AIAA 样式（编号制；AIAA Journal of Aircraft / JGCD 均用此样式）",
    reporting_standards={
        "airworthiness": "适航遵循 FAR / CS-25 / EASA Part 25 与 EASA Part 27",
        "human_factors": "人因遵循 ICAO Annex 1 / EASA HR / FAA HR",
        "atm": "空中交通管理遵循 ICAO Annex 6 / 11 / ICAO Doc 4444",
        "aircraft_design": "设计与性能遵循 FAR Part 23 / 25 / CS-25",
        "simulation": "飞行仿真遵循 RTCA DO-177 / DO-200 / ARP4754A",
        "safety_management": "航空安全遵循 ICAO Doc 9859 / EASA Part OPS",
        "meteorology": "气象数据遵循 WMO / NOAA / ECMWF 惯例",
    },
    conventions=(
        "飞行器性能（V_max、Vmin、L/D、航程、升限、爬升率）须完整报告并标注海平面/ISA 条件",
        "气动系数（C_L、C_D、C_m）须标注参考点（焦点/重心/前缘）与参考面积",
        "六自由度飞行仿真须标注参考坐标系（body/earth/earth-inertial）",
        "试验遵循 FAR Part 25 / CS-25 / EASA Part 25 等相关法规版本",
        "安全事件分类遵循 ICAO Annex 13 事件严重性分类",
        "气象数据须标注数据源与时间分辨率（1 h / 6 h / 24 h）",
        "数值结果给出均值 ± 不确定度与样本量；仿真报告网格无关性",
    ),
    key_venues=(
        "Journal of Aircraft (AIAA)",
        "Journal of Guidance, Control, and Dynamics (AIAA)",
        "Aerospace Science and Technology",
        "Journal of Air Transport Management",
        "Aviation Safety Journal",
        "SAE International Journal of Aerospace",
        "AIAA Aviation Forum",
        "AIAA SciTech",
        "ICAS (International Council of the Aeronautical Sciences)",
        "Journal of Aerospace Engineering (ASCE)",
        "Journal of Operational Research Society",
    ),
    units_and_formulas_notes=(
        "高度用 ft（海平面/ISA）；速度用 m/s、kts、Mach",
        "升力/阻力系数用 C_L、C_D；力矩系数用 C_m",
        "密度/粘度遵循 ISA 标准大气；动压用 q = ½ρV²",
        "显示公式仅在被引用时编号；行内公式避免复杂分式",
        "空域术语按 ICAO Annex 11 采用（Class A/B/C/D/E/F/G）",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("X-Plane", "Microsoft Flight Simulator (MSFS)", "FlightGear", "Prepar3d", "XFLR5", "Georgia Tech OpenVSP", "NASA CEA", "NASA XFOIL", "ONERA M6", "AVL", "OpenFOAM", "ANSYS Fluent", "Simcenter FLOEFDY", "STAR-CCM+", "MATLAB/Simulink", "Simics (Wind River)", "ARPAStar", "Gazebo", "CoppeliaSim", "CATIA", "Siemens NX", "SolidWorks", "Onshape", "FreeCAD", "WRF", "ICON (DWD)", "ECMWF"),
    category="工学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "IEEE Xplore", "AIAA Online", "NOAA NCEI", "Eurocontrol SESAR"),
)
