"""Avionics 学科论文支持：航电系统、机载计算机、ARINC 总线与机载显示/通信体裁、IEEE 样式。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="avionics",
    aliases=(
        "avionics",
        "航空电子",
        "航电",
        "航电系统",
        "机载电子",
        "机载电子系统",
        "综合航电",
        "Avionics",
        "Aeronautical Electronics",
        "Flight Instrumentation",
        "Integrated Modular Avionics",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "methods（建模、架构、标定与试验）",
            "results（性能、仿真与实测）",
            "discussion（机理与工程意义）",
            "conclusion",
            "references",
        ),
        "system_design": (
            "abstract",
            "introduction（问题与需求）",
            "requirements（需求与约束）",
            "architecture（系统/硬件/软件架构）",
            "implementation（实现与集成）",
            "validation（DO-178C / DO-254 验证）",
            "conclusion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="IEEE 样式（编号制，作者-文献编号，如 [1]、[2]）",
    reporting_standards={
        "software_safety": "软件安全性遵循 RTCA DO-178C（DAL A/B/C/D）与 DO-330",
        "hardware_safety": "硬件安全性遵循 RTCA DO-254（DAL A/B/C/D）与 DO-331",
        "environmental": "环境试验遵循 RTCA DO-160G（振动、冲击、EMC）",
        "emc": "EMC 遵循 MIL-STD-461G / RTCA DO-160G / ARINC 665",
        "networks": "机载总线遵循 ARINC 429 / ARINC 664 (AFDX) / MIL-STD-1553B",
        "diagnostics": "机载诊断遵循 ARINC 662 / ARINC 654 / DO-326A",
        "process": "开发过程遵循 ARP4754A / ARP9131A / DO-178C 过程",
    },
    conventions=(
        "航电系统须明确 DO-178C 与 DO-254 相关等级（A/B/C/D）并显式标注",
        "通信总线须明确 ARINC 429 / ARINC 664 (AFDX) / MIL-STD-1553B 版本",
        "EMC 测试遵循 MIL-STD-461G / DO-160G 并标注具体条款",
        "显示/HMI 遵循 ARINC 623 / ARINC 753 / ARINC 750",
        "数据接口须标注速率、时钟、协议与字节序",
        "故障注入与 HIL 试验须提供测试脚本、覆盖率与执行环境版本",
        "需求追踪须给出 Requirements → Code → Test 的映射（ReqID 前缀 AR-）",
    ),
    key_venues=(
        "IEEE Transactions on Aerospace and Electronic Systems",
        "IEEE Aerospace and Electronic Systems Magazine",
        "IEEE Transactions on Vehicular Technology (Avionics section)",
        "Aerospace Science and Technology",
        "Journal of Guidance, Control, and Dynamics",
        "IEEE Access (Avionics)",
        "IEEE Conference on Decision and Control (CDC)",
        "IEEE Automation and Control Conference (CAC)",
        "IEEE International Conference on Systems (ICONS)",
        "AIAA SciTech Forum (Avionics session)",
    ),
    units_and_formulas_notes=(
        "电压用 V、电流用 A、阻抗用 Ω；总线速率用 bps (bit/s)",
        "ARINC 429 帧用 BNR 编码，32 bit 帧结构须完整列出",
        "ARINC 664 报文用 AFDX 时分复用，时间片用 µs 报告",
        "EMC 频段覆盖 0 Hz–18 GHz，频段按 MIL-STD-461G 分档",
        "显示公式仅在被引用时编号；行内公式避免复杂分式",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("MATLAB/Simulink", "Simulink Embedded Coder", "ANSYS Electronics Desktop", "ANSYS HFSS", "ANSYS Maxwell", "ANSYS Icepak", "Keysight ADS", "Cadence Virtuoso", "Synopsys VCS", "Mentor ModelSim", "Lauterbach TRACE32", "dSPACE SCALEXIO", "NI VeriStand", "NI PXI", "NI Multisim", "Green Hills MULTI", "Wind River Simics", "Code Composer Studio", "Altium Designer", "OrCAD", "CST Studio Suite", "COMSOL Multiphysics", "Keysight PXI", "Rohde & Schwarz"),
    category="工学",
    databases=("OpenAlex", "Crossref", "IEEE Xplore", "RTCA DO-178C Archive", "ARINC/RTCA", "CNKI", "万方"),
)
