"""Ayurvedic medicine 学科论文支持：阿育吠陀诊断、方剂、草药化学与临床评价体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="ayurvedic_medicine",
    aliases=(
        "ayurvedic_medicine",
        "阿育吠陀医学",
        "阿育吠陀",
        "印度传统医学",
        "印度医学",
        "Vedic medicine",
        "Ayurveda",
        "Ayurvedic Medicine",
        "Indian System of Medicine",
        "Herbal Medicine",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "materials and methods（药物、剂型、剂量与试验设计）",
            "results（数据与统计）",
            "discussion（机理与临床意义）",
            "conclusion",
            "references",
        ),
        "clinical_trial": (
            "abstract",
            "introduction（临床背景与假设）",
            "methods（RCT 设计、入组标准、干预、终点）",
            "results（主要/次要终点、安全性）",
            "discussion（疗效与局限）",
            "conclusion",
            "references",
        ),
        "phytochemical": (
            "abstract",
            "introduction（植物分类与背景）",
            "materials and methods（提取、分离、表征）",
            "results（成分、含量、表征数据）",
            "discussion（生物活性与结构-活性关系）",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method（含 PRISMA 流程）",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="Vancouver 样式（编号制，作者-年份/编号混合）；临床试验遵循 ICMJE 与 CONSORT",
    reporting_standards={
        "clinical_trials": "RCT 遵循 GCP、CTRI 注册号与 ICMJE 声明；CONSORT 报告",
        "observational": "观察性研究遵循 STROBE 声明",
        "meta_analysis": "荟萃分析遵循 PRISMA 2020",
        "phytochemical": "植物化学遵循 Phytochemical Methods 与 ISO 13138 术语",
        "gmp": "药品生产遵循 AYUSH GMP / WHO GMP",
        "diagnosis": "诊断遵循 Charaka Samhita / Sushruta Samhita / Ashtanga Hridaya 经典",
        "nomenclature": "命名遵循 Indian Pharmacopoeia (Ayurvedic) 与 WHO ICD-11",
    },
    conventions=(
        "阿育吠陀处方须同时给出梵文名称与英文俗名（如 Ashwagandha / Withania somnifera）",
        "复方剂量与剂型（Churna、Avaleha、Asava、Kwatha、Taila、Ghrita）须明确",
        "成分表征须标注 LC-MS/UV-HPLC 方法（含流动相、柱、检测波长）",
        "疗效评估须结合主观量表（VAS、SDS、PHQ-9）与客观生理指标",
        "临床试验须给出 CTRI 注册号与样本量估算依据",
        "安全性报告须标注严重不良事件（SAE）与 SAE/TEAE 分类",
        "统计数据须报告 p 值、置信区间与效应量",
    ),
    key_venues=(
        "Journal of Ayurveda and Integrative Medicine",
        "Journal of Ethnopharmacology",
        "Evidence-Based Complementary and Alternative Medicine",
        "Journal of Clinical and Diagnostic Research",
        "Cureus",
        "Indian Journal of Traditional Knowledge",
        "Journal of Clinical and Diagnostic Research (JCDS)",
        "AYUSH Journal",
        "BMC Complementary and Alternative Medicine",
        "Phytomedicine",
        "Journal of Herbal Medicine",
    ),
    units_and_formulas_notes=(
        "剂量用 g/mL 或传统单位（masha/tikta）并给出换算",
        "化学成分含量用 % (w/w) 与 mg/g 双重报告",
        "LC-MS 用 m/z 与 RT（保留时间）表征",
        "统计显著性以 α=0.05 为准；多因素分析标注 p<0.05 与 Bonferroni 校正",
        "样本量按 G*Power 估算并报告 power",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("ClinicalTrials.gov", "CTRI", "ResearchGate", "EndNote", "Mendeley", "Zotero", "SPSS", "GraphPad Prism", "R/RStudio", "Jamovi", "JASP", "STATA", "Python", "NCBI BLAST", "HMDB", "KEGG", "Bruker Avance (NMR)", "Shimadzu HPLC", "Thermo Fisher GC-MS", "Bruker Vertex FTIR", "Sciex LC-MS/MS", "Malvern Zetasizer", "OpenClinica", "REDCap"),
    category="医学",
    databases=("PubMed", "OpenAlex", "Crossref", "ClinicalTrials.gov", "SCImago", "Google Scholar", "PubMed Central", "PubChem", "ChEMBL", "DrugBank"),
)
