"""Bacteriology 学科论文支持：细菌鉴定、微生物组、药敏、基因组学体裁，MLA/APA 与 ASM 样式。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="bacteriology",
    aliases=(
        "bacteriology",
        "细菌学",
        "细菌",
        "细菌学",
        "微生物学",
        "病原细菌学",
        "微生物基因组学",
        "Bacteriology",
        "Bacteria",
        "Microbiology",
        "Microbial Genomics",
        "Pathogenic Bacteria",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "materials and methods（菌株、培养、鉴定、测序）",
            "results（数据与统计）",
            "discussion（机理与意义）",
            "references",
        ),
        "taxonomic": (
            "abstract",
            "introduction（分类背景）",
            "taxonomy（新种/新属描述）",
            "phenotypic properties",
            "genomic properties",
            "phylogenetic analysis",
            "discussion",
            "references",
        ),
        "microbiome": (
            "abstract",
            "introduction",
            "materials and methods（采样、测序、质控、分析流程）",
            "results（α/β 多样性、物种组成、功能）",
            "discussion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="ASM 样式（编号制，作者-文献编号）；分子系统学遵循 MIxS/MIAGE",
    reporting_standards={
        "nomenclature": "命名遵循《国际原核生物命名法规》ICNP（含 EIMB）",
        "strain_deposition": "菌株须存放至少两个 ATCC/DSMZ/JCM 保藏中心",
        "genome_submission": "基因组须上传 GenBank（登录号）与 SRA（SRR 号）",
        "16s_rna": "16S rRNA 分析须遵循 MIxS 与 QIIME2 报告规范",
        "antimicrobial": "药敏试验遵循 CLSI M07/M08 与 EUCAST 标准",
        "bioinformatics": "流程须遵循 MAGE 与 MIAGE/MIxS 声明",
        "safety": "涉及病原菌须遵循 BSL-2/3 生物安全级别",
    },
    conventions=(
        "菌株命名遵循《国际原核生物命名法规》ICNP，须含 ATCC/DSMZ/JCM 编号与模式株",
        "基因组数据须上传 GenBank（登录号）与 SRA（SRR 号）",
        "16S rRNA 分析须明确扩增引物、去嵌合体方法与分析平台（QIIME2/mothur）",
        "表型试验须给出温度、培养基成分、pH、厌氧条件与培养时间",
        "药敏试验须遵循 CLSI / EUCAST 标准并给出 MIC 值",
        "多样性分析须报告 α（Shannon/Simpson/Chao1）与 β（Bray-Curtis/UniFrac）",
        "统计显著性须标注 p 值、置信区间与多重检验校正（FDR/Bonferroni）",
    ),
    key_venues=(
        "Journal of Bacteriology (ASM)",
        "mBio (ASM)",
        "Nature Reviews Microbiology",
        "Nature Microbiology",
        "PNAS",
        "PLoS Pathogens",
        "Environmental Microbiology",
        "Applied and Environmental Microbiology",
        "Microbiology Spectrum",
        "Trends in Microbiology",
        "ISME Journal",
        "Microbiome",
    ),
    units_and_formulas_notes=(
        "菌落用 CFU/mL；生长速率用 OD600；浓度用 μg/mL、mg/L",
        "分子量用 Da；等电点用 pI；等值点标注",
        "序列比对用 e-value、identity % 与 coverage %",
        "统计显著性 α=0.05；多重检验用 FDR<0.05",
        "公式用 amsmath；分子方程须编号",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("Bruker Biotyper (MALDI-TOF MS)", "Shimadzu TOF-5000", "BioMérieux VITEK 2", "BD Phoenix", "Beckman MicroScan", "QIIME2", "mothur", "MEGA", "PAST", "PRIMER", "NCBI BLAST", "CLC Genomics Workbench", "Geneious", "Sequencher", "SILVA", "Greengenes2", "BacDive", "Bio-Rad CFX96", "Thermo Fisher Q Exactive", "Bruker timsTOF", "BD FACSCanto", "Zeiss Axio", "Nikon Eclipse", "Illumina MiSeq", "Oxford Nanopore MinION", "GraphPad Prism", "SPSS", "R", "BioPython"),
    category="医学",
    databases=("PubMed", "OpenAlex", "Crossref", "GenBank", "SRA", "NCBI Taxonomy", "BacDive", "LPSN", "UniProt", "KEGG"),
)
