"""Baking 学科论文支持：烘焙工艺、面团流变、烘焙品质、配方优化体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="baking",
    aliases=(
        "baking",
        "烘焙",
        "面包制作",
        "糕点烘焙",
        "面点制作",
        "烘焙工程",
        "Baking",
        "Bakery",
        "Bread Making",
        "Pastry",
        "Bakery Engineering",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "materials and methods（原料、配方、工艺、仪器）",
            "results（品质、流变、感官、保质期）",
            "discussion（机理与工程意义）",
            "references",
        ),
        "formulation": (
            "abstract",
            "introduction（配方背景）",
            "materials and methods（配方设计与 DOE）",
            "results（感官/物理/流变/微生物）",
            "optimization（RSM/ANOVA/优化）",
            "conclusion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="APA 7 样式；食品科学遵循 Elsevier 期刊规范",
    reporting_standards={
        "sensory": "感官评价遵循 ISO 8586 / ISO 4120 / ISO 13299",
        "water_activity": "水分活度遵循 AACC 2015.25",
        "dough_rheology": "面团流变遵循 AACC Farinograph / Alveograph / Chopin Extruder",
        "bakery_quality": "烘焙品质遵循 AACC 10-33 / 10-43 / 54-32",
        "microbiology": "微生物遵循 ISO 4833 / ISO 21527 / ISO 1129",
        "shelf_life": "保质期遵循 ISO 5667 / Accelerated Shelf-Life Test",
        "nutrition": "营养成分遵循 ISO 14984 / ISO 13583",
    },
    conventions=(
        "配方须以 baker's % 报告（各料占面粉量百分比）",
        "烤炉参数（温度、湿度、时间、蒸汽）须完整报告",
        "面团状态须用 Farinograph/Alveograph 参数表征（含水量、稳定时间、W 值）",
        "水分活度（aw）与水分含量（%）须分开报告",
        "感官评价须遵循 ISO 8586 并给出评价员数量与培训时长",
        "保质期须给出测试条件（温度、湿度）与方法（加速/动态）",
        "数值结果给出均值 ± 标准差与样本量",
    ),
    key_venues=(
        "Journal of Cereal Science",
        "LWT - Food Science and Technology",
        "Journal of Food Engineering",
        "Food Research International",
        "Critical Reviews in Food Science and Nutrition",
        "European Food Research and Technology",
        "International Journal of Food Microbiology",
        "Food Microbiology",
        "Food Chemistry",
        "Journal of the Science of Food and Agriculture",
        "Journal of Texture Studies",
    ),
    units_and_formulas_notes=(
        "配方用 baker's %；水分活度用 aw (0-1)",
        "面团参数：含水量 %、稳定时间 min、W 值、P/L 比",
        "感官评分用 9 点 Hedonic scale",
        "保质期用天/月并标注温度",
        "统计显著性 α=0.05；多重比较用 Tukey HSD",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "艺术作品", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("Rational iCombi", "Rational iControl", "MixBoss mixer", "Hobart MixMaster", "WEM (Wenger & Mettler)", "Unox Proofer", "OCEAN Proofer", "FIMAC Proofer", "Buhler Milling", "Buhler ProCereal", "Rotronic Testro", "Rotronic AquaLab", "TA.XT Plus (Texture Technologies)", "Chroma Meter CR-400 (Konica Minolta)", "Anton Paar Viscotherm", "Anton Paar Rheometer", "Thermopro", "Hanna Instruments pH Meter", "SPSS", "R", "Excel", "Adobe Photoshop", "Canva"),
    category="工学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "Google Scholar", "ScienceDirect"),
)
