"""Ballet 学科论文支持：编舞、动作分析、舞蹈记谱、舞台设计体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="ballet",
    aliases=(
        "ballet",
        "芭蕾",
        "古典芭蕾",
        "芭蕾舞",
        "芭蕾舞蹈",
        "芭蕾艺术",
        "Ballet",
        "Classical Ballet",
        "Ballet Dance",
        "Choreography",
        "Dance Notation",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "methods（记谱/动作捕捉/实验方法）",
            "results（编舞/训练/运动学）",
            "discussion（艺术/科学/文化意义）",
            "references",
        ),
        "choreographic": (
            "abstract",
            "introduction（创作背景）",
            "structure（结构、段落、主题）",
            "movement（动作语言与技巧）",
            "musical and dramatic (音乐与戏剧性)",
            "staging (舞台与编队)",
            "references",
        ),
        "historical": (
            "abstract",
            "introduction（历史背景）",
            "period and context（时期与背景）",
            "works and choreographers（作品与编舞家）",
            "interpretation（阐释与比较）",
            "conclusion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="APA 7 样式；舞蹈记谱遵循 Labanotation 与 Benesh Movement Notation 标准",
    reporting_standards={
        "notation": "记谱遵循 Labanotation 或 Benesh Movement Notation 国际编码",
        "notation_safety": "训练与作品遵循 IAB/ABD 安全指导（Ballet Injuries 分级）",
        "motion_capture": "动作捕捉遵循 BVH/FAV/C3D 标准格式",
        "scoring": "乐谱遵循标准五线谱与 Sibelius/Finale 约定",
        "costume": "服装 3D 遵循 CLO 3D / Marvelous Designer 建模规范",
        "video": "排练视频须标注时长、镜头、机位与时间码",
        "ethics": "涉儿童舞者研究须遵循 IRB/伦理审查",
    },
    conventions=(
        "舞蹈动作须遵循 Labanotation 或 Benesh Movement Notation 记录",
        "训练课程须标注等级与教材来源（Vaganova/Radetsky/Bournonville/Cecchetti）",
        "音乐记谱须采用标准五线谱，调性与拍号显式标注",
        "编舞作品须标注首演时间与演出地点",
        "舞美与服装设计须附 3D 或 2D 设计稿",
        "训练/表演视频须标注时间码与镜头位置",
        "涉及儿童演员的伦理审查与同意书须附",
    ),
    key_venues=(
        "Dance Research Journal (Taylor & Francis)",
        "International Journal of Dance Science and Technology",
        "Journal of Dance Medicine and Science",
        "Dance Culture: Theory and Practice",
        "Choreographica",
        "Journal of Dance Science",
        "Dance Notation Quarterly",
        "International Review of Movement Notation (IRNM)",
        "Dance Research Society",
        "Bournonvile Bulletin",
        "International Association for the Study of Choreology and Dance Notation (IASD)",
    ),
    units_and_formulas_notes=(
        "时间用秒；节奏用 bpm",
        "动作速度用 m/s；高度用 m",
        "力度用 Laban Effort（Strong/Strong+Soft/Strong-Soft-Sharp）",
        "音乐用标准五线谱与 MIDI 编码",
        "视频用时间码 HH:MM:SS:FF",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "艺术作品", "教案与教材", "译文", "报告", "数据集"),
    tools=("Vicon", "OptiTrack", "Xsens", "Qualisys", "MotionBuilder (Autodesk)", "Maya (Autodesk)", "Blender", "Unreal Engine", "CLO 3D", "Marvelous Designer", "Motif Movement Notation", "Labanotation", "Benesh Movement Notation", "Adobe Audition", "Pro Tools", "Ableton Live", "Finale", "Sibelius", "MuseScore", "Adobe Premiere", "DaVinci Resolve", "Adobe Photoshop", "Adobe Illustrator", "Notion", "Airtable"),
    category="艺术学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "Google Scholar", "Choreography Online", "Labanotation Archive"),
)
