"""Banking, Finance and Investment 学科论文支持：投资组合、资产配置、估值、投资决策体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="banking_finance_and_investment",
    aliases=(
        "banking_finance_and_investment",
        "银行金融与投资",
        "银行金融投资",
        "金融与投资",
        "投资管理",
        "投资组合管理",
        "Banking Finance and Investment",
        "Banking Finance Investment",
        "Investment Management",
        "Portfolio Management",
        "Asset Allocation",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "methods（模型、数据、识别策略）",
            "results（估计、稳健性、异质性）",
            "discussion（经济含义与政策启示）",
            "conclusion",
            "references",
        ),
        "investment_analysis": (
            "abstract",
            "introduction（投资背景）",
            "company analysis（行业、公司、财务）",
            "valuation（估值方法与假设）",
            "risk analysis（风险与情景）",
            "recommendation",
            "references",
        ),
        "portfolio_review": (
            "abstract",
            "introduction",
            "portfolio construction",
            "performance attribution",
            "risk assessment",
            "recommendations",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="APA 7 样式；投资研究遵循 CFA Institute 与 IAI 期刊惯例",
    reporting_standards={
        "accounting": "财务数据遵循当地会计准则（IFRS/CAS/US GAAP）与审计意见",
        "portfolio": "投资组合遵循 IAI Performance Presentation 标准",
        "valuation": "估值遵循 IAS 36 / ASC 820 公允价值层级",
        "risk": "风险披露遵循 GARP FMVA 与 Barra 模型规范",
        "regulation": "监管数据标注发布机构（PBoC / CBIRC / SEC / FINRA）",
        "performance": "收益分析区分会计收益与经济收益（Sharpe / Sortino / IR）",
    },
    conventions=(
        "投资组合须标注风格（大/中/小盘，价值/成长，主动/被动）",
        "基准须明确（沪深 300 / MSCI China / Wind 全 A / CSI 500）",
        "风险须给出 α、β、Sharpe、Sortino、Tracking Error、Information Ratio",
        "估值须列出可比公司与倍数方法（PE/PB/PS/EV-EBITDA）",
        "数据须标注发布机构与频率（日/周/月/季/年）",
        "回测须标注样本区间与滑点假设",
        "估值方法须说明（DCF/DDM/可比公司法/剩余收益）",
        "实证结果须报告系数、标准误、t 值与样本区间",
    ),
    key_venues=(
        "Journal of Banking and Finance",
        "Journal of Financial Economics",
        "Journal of Portfolio Management",
        "Financial Analysts Journal (CFA)",
        "Journal of Financial Research",
        "Review of Financial Studies",
        "Journal of Financial Intermediation",
        "Journal of Investing",
        "Journal of Financial Management",
        "Journal of Financial Economic Policy",
        "Journal of Portfolio Management Research",
    ),
    units_and_formulas_notes=(
        "金额用人民币/美元；收益率用 %",
        "风险用波动率 %；Sharpe/Sortino 无单位",
        "估值倍数用 PE/PB/PS/EV-EBITDA（倍）",
        "样本量与置信区间须标注",
        "统计显著性 α=0.05；系数报告 t 值",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "教案与教材", "报告", "数据集"),
    tools=("Bloomberg Terminal", "Bloomberg BQuant", "Refinitiv", "Refinitiv Eikon", "LSEG", "FactSet", "S&P Capital IQ", "Morningstar Direct", "Barra", "MSCI", "Axioma", "Wind (万得)", "Choice (东方财富)", "Murex", "Calypso", "Capital IQ", "Excel", "R", "Python", "Stata", "MATLAB", "Tableau"),
    category="管理学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "Bloomberg", "Refinitiv", "Wind (万得)", "S&P Capital IQ", "Morningstar", "Barra"),
)
