"""Banking and finance 学科论文支持：银行管理、风险管理、金融监管、银行治理体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="banking_and_finance",
    aliases=(
        "banking_and_finance",
        "银行与金融",
        "银行金融",
        "银行学",
        "金融学",
        "金融监管",
        "Banking",
        "Banking and Finance",
        "Banking Finance",
        "Financial Regulation",
        "Bank Management",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "methods（数据、模型、识别策略）",
            "results（估计、稳健性、异质性）",
            "discussion（经济含义与政策启示）",
            "conclusion",
            "references",
        ),
        "empirical": (
            "abstract",
            "introduction",
            "theoretical framework",
            "model and data",
            "empirical results",
            "robustness checks",
            "conclusion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="APA 7 样式；金融实证遵循 AER / JFE / JF 期刊惯例",
    reporting_standards={
        "accounting": "财务数据遵循当地会计准则（IFRS/CAS/US GAAP）与审计意见",
        "risk": "风险敞口遵循 Basel III / IV 支柱 2 划分（信用/市场/操作）",
        "liquidity": "流动性风险给出 IRR 与 NRR 计算",
        "pricing": "定价模型标注参考基准与期限结构（LPR / SOFR / LIBOR）",
        "regulation": "监管数据标注发布机构（PBoC / CBIRC / FRB / ECB / BIS）",
        "earnings": "收益分析区分会计收益与经济收益（EVA/RAROC）",
        "empirical": "实证研究遵循 CRANES / CONSORT 报告规范",
    },
    conventions=(
        "财务数据须遵循当地会计准则（IFRS/CAS/US GAAP）并标注审计意见",
        "风险敞口须按监管口径（Basel III/IV 支柱 2）划分",
        "流动性风险须给出 IRR 与 NRR 计算",
        "定价模型须标注参考基准（LPR/SOFR/LIBOR）与期限结构",
        "监管数据须标注发布机构（PBoC / CBIRC / FRB / ECB / BIS）与发布日期",
        "收益分析须区分会计收益与经济收益",
        "实证结果须报告系数、标准误、t 值、R² 与样本区间",
        "计量方法须说明（OLS/IV/面板/时间序列）与识别策略",
    ),
    key_venues=(
        "Journal of Banking and Finance",
        "Journal of Financial Economics",
        "Journal of Finance",
        "Review of Financial Studies",
        "Journal of Financial Intermediation",
        "Review of Banking and Finance",
        "Quarterly Journal of Economics",
        "American Economic Review",
        "Journal of Financial Markets",
        "Financial Management",
        "Journal of Banking and Financial Markets",
    ),
    units_and_formulas_notes=(
        "金额用人民币/美元；利率用 % 或 bp",
        "风险用 VaR / ES / 标准差",
        "流动性用 LCR / NSFR",
        "资本充足率用 %（一级核心资本）",
        "统计显著性 α=0.05；系数报告 t 值或 z 值",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "教案与教材", "报告", "数据集"),
    tools=("Bloomberg Terminal", "Bloomberg BQuant", "Refinitiv (Reuters)", "Refinitiv Eikon", "LSEG", "FactSet", "S&P Capital IQ", "Murex", "Calypso", "Wind (万得)", "Choice (东方财富)", "Morningstar Direct", "Barra", "MSCI", "Worldscope (Bureau van Dijk)", "Orbis (Bureau van Dijk)", "Excel", "R", "Python", "Stata", "MATLAB", "Tableau", "Power BI"),
    category="经济学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "Bloomberg", "Refinitiv", "Wind (万得)", "S&P Capital IQ", "BIS", "IMF"),
)
