"""Bank teller studies 学科论文支持：柜面业务、客户识别、反洗钱、柜台差错体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="bank_teller_studies",
    aliases=(
        "bank_teller_studies",
        "银行柜员学",
        "银行柜员",
        "柜员",
        "银行前台",
        "银行柜台",
        "银行柜面",
        "Bank Teller",
        "Bank Teller Studies",
        "Bank Front Office",
        "Retail Banking Operations",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "methods（操作、差错率、客户服务）",
            "results（数据、统计、案例）",
            "discussion（运营与合规意义）",
            "references",
        ),
        "case_study": (
            "abstract",
            "introduction",
            "case description（柜面场景）",
            "analysis（差错/流程/客户投诉）",
            "recommendations",
            "conclusion",
            "references",
        ),
        "operational": (
            "abstract",
            "introduction",
            "methodology（操作规范、系统、流程）",
            "results（差错率、办理时长、满意度）",
            "recommendations",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="APA 7 样式；金融报告遵循 CFA Institute 与 EFRAG 声明",
    reporting_standards={
        "aml": "反洗钱遵循 FATF 40 项建议与当地 FRT 规定",
        "kyc": "客户识别遵循 ISO 22247 与当地 KYC 三级标准",
        "cash_handling": "现金处理遵循 ISO 15421 / ISO 13207",
        "banking_operations": "柜面业务遵循当地银行业监管（PBoC/SFC/OCC）",
        "complaint_handling": "客户投诉遵循 ISO 10002",
        "error_reporting": "差错率遵循 Basel Committee 报告规范",
    },
    conventions=(
        "现金处理与清点须遵循当地反洗钱法规与 ISO 15421（纸币）",
        "客户身份识别须遵循 KYC 三级标准并标注证件类型与有效期",
        "大额/可疑交易报告须遵循当地 FRT 规定并标注金额阈值",
        "柜面业务差错率须给出统计方法（分子/分母/统计周期）",
        "客户投诉处理须记录处置时间与结果",
        "培训材料须给出学时、考核标准与通过率",
        "数值结果给出均值 ± 标准差与样本量",
    ),
    key_venues=(
        "Bank Service and Operations Management (BSOM)",
        "Journal of Bank Marketing",
        "International Journal of Bank Marketing",
        "Review of Banking and Financial Services",
        "Bankers Trust Journal",
        "Journal of Retail Banking Services",
        "Global Business and Finance Review",
        "International Journal of Banking and Financial Economics",
        "Journal of Financial Management",
        "Journal of Financial Services Marketing",
        "Journal of the Banking Institute",
    ),
    units_and_formulas_notes=(
        "金额用人民币/美元；柜面处理用交易笔数",
        "差错率用 %；投诉率用件/万笔",
        "处理时长用秒/分钟",
        "客户满意度用 NPS/CSAT",
        "统计显著性 α=0.05",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "艺术作品", "教案与教材", "报告", "数据集"),
    tools=("Temenos Transact", "Temenos Fusion", "Finacle (TCS)", "Flexcube (Temenos)", "Jack Henry Focus", "Fiserv TotalBanking", "FIS Profile", "NCR Voyix POS", "Diebold Nixdorf POS", "Fiserv POS", "NICE Actimize (AML)", "SAI360", "Fenergo", "Trulioo (KYC)", "Persona (KYC)", "Onfido (KYC)", "SWIFT Alliance", "SWIFT Financial Messaging", "Wind (万得)", "Refinitiv", "Bloomberg", "Excel", "SPSS", "Tableau", "Power BI"),
    category="管理学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "Wind (万得)", "Bloomberg", "Refinitiv"),
)
