"""Bar service 学科论文支持：酒吧运营、调酒工艺、餐饮管理、酒水服务体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="bar_service",
    aliases=(
        "bar_service",
        "酒吧服务",
        "酒吧",
        "酒吧服务学",
        "酒吧管理",
        "餐饮酒吧",
        "酒保服务",
        "Bar Service",
        "Bar Studies",
        "Bar Management",
        "Beverage Service",
        "Bartending",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "methods（操作、顾客体验、数据分析）",
            "results（运营、销售、满意度）",
            "discussion（管理与合规意义）",
            "references",
        ),
        "operational": (
            "abstract",
            "introduction",
            "methodology（流程、系统、培训）",
            "results（销售额、复购率、投诉率）",
            "recommendations",
            "references",
        ),
        "case_study": (
            "abstract",
            "introduction",
            "case description（酒吧/餐饮场景）",
            "analysis（运营/服务/顾客体验）",
            "recommendations",
            "conclusion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope and method",
            "state of the art",
            "gaps and outlook",
            "references",
        ),
    },
    citation_style="APA 7 样式；餐饮行业报告遵循 CFA / EFRAG 惯例",
    reporting_standards={
        "food_safety": "食品安全遵循 HACCP / GMP 与当地食品安全法",
        "alcohol_service": "饮酒服务遵循当地法规与 IBA（国际调酒师协会）",
        "alcohol_by_volume": "酒精度用 ABV（Alcohol by Volume %）",
        "drink_standards": "调酒工艺遵循 IBA (International Bartenders Association) 标准",
        "customer_service": "客户服务遵循 ISO 10002",
        "inventory": "库存管理遵循 POS 系统规范",
    },
    conventions=(
        "酒单与饮品须遵循 IBA (International Bartenders Association) 标准",
        "酒精含量与酒精度（ABV）须完整报告",
        "食品安全须遵循 HACCP 与 GMP",
        "饮酒服务须遵循当地法规（含 KYC 年龄验证）",
        "调酒工艺须标注计量单位（ml/oz）、比例、方法与摇/调/滤",
        "数据分析须给出样本量与置信区间",
        "数值结果给出均值 ± 标准差与样本量",
    ),
    key_venues=(
        "International Journal of Hospitality Management",
        "Cornell Hospitality Quarterly",
        "International Journal of Contemporary Hospitality Management",
        "Journal of Wine Research (Emerald)",
        "International Journal of Wine Business Research (Emerald)",
        "Journal of Foodservice Business Research",
        "Tourism Management",
        "Journal of Retailing and Consumer Services",
        "International Journal of Tourism and Leisure Research",
        "Journal of Sustainable Tourism",
        "Journal of Food Science and Technology",
    ),
    units_and_formulas_notes=(
        "酒精度用 ABV %；体积用 ml/oz",
        "销售用件/小时；客单价用元/笔",
        "复购率用 %；投诉率用件/千笔",
        "顾客满意度用 NPS/CSAT（1-10 分）",
        "统计显著性 α=0.05",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "艺术作品", "教案与教材", "报告", "数据集"),
    tools=("Toast POS", "Square POS", "Aloha POS (NCR)", "Lightspeed POS", "Clover POS", "Revel POS", "MarketMan", "OpenTable", "Resy", "Tock", "SevenRooms", "Toast Academy", "Toast Loyalty", "Adobe Photoshop", "Adobe Illustrator", "Canva", "Figma", "Excel", "SPSS", "Tableau", "Power BI"),
    category="管理学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "Google Scholar", "ScienceDirect", "Emerald"),
)
