"""Basic nursing 学科论文支持：基础护理/临床护理体裁、APA/Vancouver 引用样式与护理学记法注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="basic_nursing",
    aliases=(
        "basic_nursing",
        "basic nursing",
        "基础护理",
        "基础护理学",
        "临床护理",
        "fundamentals of nursing",
        "nursing fundamentals",
        "护理基础",
        "临床护理学",
        "clinical nursing",
        "护理学",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与临床问题）",
            "literature review（文献综述）",
            "methods（方法：设计、样本、工具、伦理）",
            "results（结果）",
            "discussion（讨论与护理启示）",
            "conclusion（结论）",
            "references",
        ),
        "randomized_controlled_trial": (
            "abstract",
            "introduction",
            "methods（设计、样本、干预、结局、随机化）",
            "results",
            "discussion",
            "conclusion",
            "references",
        ),
        "case_report": (
            "abstract",
            "introduction",
            "case presentation",
            "discussion",
            "references",
        ),
        "systematic_review": (
            "abstract",
            "introduction",
            "methods（检索策略、纳入排除、质量评估）",
            "results（研究特征、合并效应）",
            "discussion",
            "references",
        ),
    },
    citation_style="APA 7 或 Vancouver 样式（作者-年份或作者-编号，按期刊规范）",
    reporting_standards={
        "RCT": "随机对照试验遵循 CONSORT 声明",
        "case_report": "病例报告遵循 CARE 清单",
        "systematic_review": "系统综述遵循 PRISMA 声明",
        "qualitative": "质性研究遵循 COREQ 或 SRQR",
        "cross_sectional": "横断面研究遵循 STROBE",
        "ethics": "伦理遵循Declaration of Helsinki 与 IRB 审批",
    },
    conventions=(
        "研究必须说明 IRB 伦理审批编号与知情同意流程",
        "被试的年龄、性别、BMI、诊断、护理周期须用表格清晰报告",
        "样本量计算须报告效应量、显著性水平与把握度",
        "护理干预须描述频次、时长、操作者资质与训练时长",
        "统计方法须报告检验类型、显著性水平、缺失数据处理与软件版本",
        "结果须报告均值±SD、CI、p 值与效应量，禁止仅报告显著性",
    ),
    key_venues=(
        "International Journal of Nursing Studies",
        "Journal of Advanced Nursing",
        "Nurse Education Today",
        "Journal of Clinical Nursing",
        "Journal of Nursing Scholarship",
        "Nursing & Critical Care",
        "Journal of Clinical Nursing",
        "Nursing Outlook",
        "Nurse Researcher",
    ),
    units_and_formulas_notes=(
        "体温用 °C（口腔/直肠/腋下），疼痛评分 0-10 NRS",
        "血压用 mmHg，脉搏用次/分，呼吸用次/分",
        "BMI 用 kg/m²，肌力分级 0-5 级（MRC 分级）",
        "给药剂量用 mg/kg 或 mg/m²，注明给药途径与频次",
        "统计结果用 M±SD 或中位数[P25, P75]，p<0.05 视为显著",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("Nightingale SimMan 3G Plus", "Laerdal Sim Man 3G", "Laerdal SimSkills", "Nursing Interventions Classification (NIC)", "Nursing Outcomes Classification (NOC)", "North American Nursing Diagnosis Association (NANDA-I)", "PROMIS (Patient-Reported Outcomes Measurement Information System)", "Epic EHR (Electronic Health Records)", "Cerner PowerChart", "Meditech Expanse", "Allscripts Epic", "UpToDate", "CINAHL Plus with Full Text", "Clinical Nursing Research (CNR)", "Nursing Center", "Ovid", "SPSS 26", "R (nursingstats package)", "JASP", "Stata 17", "SAS 9.4", "NVivo 14", "ATLAS.ti", "Qualtrics", "REDCap", "OpenClinica", "Power Analysis Calculator", "G*Power", "R Commander", "Minitab 21", "SAS Enterprise", "SPSS Modeler", "Nursing Education Journal", "Nursing Times", "Journal of Advanced Nursing", "Nurse Today"),
    category="医学",
    databases=("PubMed", "CINAHL", "Cochrane", "CNKI", "万方", "OpenAlex", "Medline WebSTAT", "MEDLINE/PubMed", "Cochrane Library", "Web of Science", "Scopus"),
)
