"""Basic skills in agriculture 学科论文支持：基础农业技能体裁、APA 引用样式与农业技能记法注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="basic_skills_in_agriculture",
    aliases=(
        "basic_skills_in_agriculture",
        "basic agriculture",
        "基础农业技能",
        "农业基础",
        "basic farming skills",
        "smallholder agriculture",
        "agricultural extension",
        "small-scale farming",
        "小农农业",
        "农业推广",
        "agriculture skills",
        "basic agricultural practices",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与农业问题）",
            "literature review（文献综述）",
            "materials and methods（试验设计、样本、工具）",
            "results（结果）",
            "discussion（讨论与农业启示）",
            "conclusion（结论）",
            "references",
        ),
        "field_trial": (
            "abstract",
            "introduction",
            "site and materials（田间试验地点与材料）",
            "methods（设计、处理、观察指标）",
            "results",
            "discussion",
            "references",
        ),
        "extension_report": (
            "abstract",
            "introduction",
            "extension activities（推广活动）",
            "results（成效评估）",
            "recommendations（建议）",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "main developments（农业/推广综述）",
            "outlook（趋势展望）",
            "references",
        ),
    },
    citation_style="APA 7（作者-年份；Agricultural Systems 遵循 Elsevier 规范）",
    reporting_standards={
        "field_trial": "田间试验遵循 CONSORT 与随机化原则",
        "extension_evaluation": "农业推广评估遵循美国教育评估标准（SEA）",
        "survey": "农户调查遵循 AAPOR 报告规范",
        "systematic_review": "系统综述遵循 PRISMA 声明",
        "ethics": "涉及农户的研究须取得知情同意",
    },
    conventions=(
        "试验地点须报告经纬度、海拔、气候区、土壤类型、试验面积",
        "作物品种须报告品系名、来源、播种密度与播期",
        "处理须明确品种、施肥量（kg/ha）、灌溉量（mm）与施药剂量",
        "试验设计须报告区组、重复数、随机化方法（如 RCB、CRD）",
        "统计方法须报告检验类型、显著性水平、多重比较校正方法",
    ),
    key_venues=(
        "Agricultural Systems",
        "Journal of Agricultural Education",
        "Agriculture, Ecosystems & Environment",
        "Journal of Rural Studies",
        "Food Security",
        "Journal of Extension and Community Learning",
        "Journal of Agricultural and Applied Economics",
        "Journal of Rural Development",
        "Journal of Soil and Water Conservation",
        "Journal of Experimental Agriculture",
    ),
    units_and_formulas_notes=(
        "产量用 t/ha 或 kg/m²；面积用 ha 或 m²；温度用 °C；降水用 mm",
        "施肥量用 kg/ha，注明 N:P:K 比例；pH 无量纲",
        "土壤养分用 mg/kg 或 g/kg，注明测试方法",
        "试验设计用 RCB、CRD、LSD、Tukey 等校正方法",
        "统计结果用 M±SD、p 值与 CI，p<0.05 视为显著",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("SPSS 26", "R (agricolae, agri4R)", "JASP", "Stata 17", "SAS 9.4 (PROC GLM)", "Minitab 21", "R Commander", "Open Plant Phenotyping Platform", "GlobalHabitat", "Global Soil Carbon Database", "Soil Survey Geographic Database (SSURGO)", "WorldCropModel (Lund University)", "OpenMeteo", "Meteostat", "AgMIP", "FAO SoilGridded", "NASA POWER", "Copernicus CDS (CLMS)", "Copernicus Sentinel-1", "Copernicus Sentinel-2", "Sentinel Hub", "Google Earth Engine", "ArcGIS Pro", "QGIS", "GRASS GIS", "ENVI", "ENVI 5", "Landsat 8", "Landsat 9", "MODIS", "Hyperspectral Camera", "Multispectral Camera", "Thermal Imaging Camera", "Drone (DJI Mavic 3)", "Drone (DJI Phantom 4 RTK)", "Drone (DJI Matrice 300 RTK)", "Drone (Parrot Anafi)", "Drone (Skydio 2+)", "Drone (Autel EVO II)", "Drone (DJI Agras T30)", "Drone (DJI Agras T40)", "Drone (DJI Agras T50)", "Drone (XAG R150)", "Drone (XAG R100)"),
    category="农学",
    databases=("OpenAlex", "CNKI", "万方", "PubMed", "CABI"),
)
