"""Beauty therapy 学科论文支持：美容/皮肤护理/美容仪器体裁、APA 引用样式与美容学记法注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="beauty_therapy",
    aliases=(
        "beauty_therapy",
        "beauty therapy",
        "美容疗法",
        "美容治疗",
        "beauty science",
        "skincare",
        "皮肤护理",
        "esthetics",
        "cosmetology",
        "aesthetic medicine",
        "aesthetic therapy",
        "beauty",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与美容问题）",
            "literature review（文献综述）",
            "materials and methods（工艺方法、被试、仪器）",
            "results（结果与仪器测量）",
            "discussion（讨论与美容启示）",
            "conclusion（结论）",
            "references",
        ),
        "clinical_trial": (
            "abstract",
            "introduction",
            "methods（设计、样本、干预、结局）",
            "results",
            "discussion",
            "conclusion",
            "references",
        ),
        "case_study": (
            "abstract",
            "introduction",
            "case description（案例背景）",
            "treatment（治疗工艺）",
            "results（结果与观察）",
            "discussion（反思与改进）",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "main developments（美容/皮肤学综述）",
            "outlook（趋势展望）",
            "references",
        ),
    },
    citation_style="APA 7（作者-年份；IJCS 遵循 Elsevier 规范，Cosmetics 遵循 MDPI 规范）",
    reporting_standards={
        "clinical_trial": "临床试验遵循 CONSORT 声明",
        "case_study": "案例研究遵循 SAGER 案例报告规范",
        "survey": "顾客满意度调查遵循 AAPOR 报告规范",
        "systematic_review": "系统综述遵循 PRISMA 声明",
        "device": "美容仪器研究遵循 ISO 14971 与设备性能报告规范",
    },
    conventions=(
        "被试照片须取得书面知情同意，注明匿名化处理与拍摄角度",
        "仪器型号须标注品牌 + 型号 + 波长/功率/脉宽等关键参数",
        "化妆品成分须列出 INCI 名称、浓度与辅料，避免仅写商品名",
        "仪器治疗须报告能量密度（J/cm²）、脉冲频率、治疗时长与次数",
        "皮肤测试须报告测试仪器（如 VISIA、Cutometer）、测试条件与标准化时间",
        "涉及皮肤刺激/敏感度的建议须标注证据等级",
    ),
    key_venues=(
        "International Journal of Cosmetic Science",
        "Journal of Cosmetic Science",
        "Cosmetics",
        "Journal of Cosmetic Dermatology",
        "Lasers in Surgery and Medicine",
        "Dermatologic Surgery",
        "Lasers in Medical Science",
        "Journal of Cosmetic and Laser Therapy",
        "Journal of Drugs in Dermatology",
        "Skin Pharmacology and Physiology",
    ),
    units_and_formulas_notes=(
        "能量密度用 J/cm²；波长用 nm；频率用 Hz 或 kHz；功率用 W",
        "pH 无量纲；含水量用 % 或 g/m²；温度用 °C",
        "皮肤弹性指标用 R2/R5 或 Ua/Ue，注明测试仪器",
        "色素度（L*、a*、b*）用 CIE L*a*b* 色度系统",
        "统计结果用 M±SD、p 值与 CI，p<0.05 视为显著",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "艺术作品", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("VISIA Complex (Canfield Scientific)", "Cutometer MPA 580 (Courage+Khazaka)", "Corneometer CM 825 (Courage+Khazaka)", "Sebumeter SM 815 (Courage+Khazaka)", "Tonometer (Courage+Khazaka)", "Cutometer MPA 560 (Courage+Khazaka)", "Kanon Digital Colorimeter (Konica Minolta CM-3600A)", "Colorimeter CM-700d (Konica Minolta)", "Spectrophotometer CM-5 (Konica Minolta)", "Fractall 1-2 (Delskym)", "Spectroskym (Delskym)", "Skin Analyzer (Delskym)", "Dermoscope DermLite III (3DERM)", "Dermoscope DermaScope 2 (Heine Optic-Heck)", "Visia Face Camera (Canfield)", "Meditec (Meditec Ltd)", "Fotona Sp Dynamis", "Fotona StarWalker (Fotona)", "Cynosure Picosure (Cynosure)", "Cynosure UltraPulse (Cynosure)", "Cynosure Apogee", "Candela GentleMax Pro (Candela Medical)", "Candela GentleYAG Pro", "Lumenis UltraPulse (Lumenis)", "Lumenis M22", "Lumenis Xeo (Lumenis)", "Alma Accent Prime (Alma Lasers)", "Alma Acousti Shaping", "Solta Venus Freeze Plus (Solta Medical)", "Solta Venus Legend", "HydraFacial MD", "Dermapen 4", "Fraxel Restore (Solta)", "Fraxel Dual (Solta)", "Clear + Brilliant (Cutera)", "Clear + Brilliant HD", "Clear + Brilliant Total", "CO2 Laser", "PicoSure (Cynosure)", "Theralase (Cynosure)"),
    category="管理学",
    databases=("OpenAlex", "CNKI", "万方", "PubMed"),
)
