"""Beer brewing 学科论文支持：啤酒酿造工艺体裁、APA 引用样式与酿造学记法注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="beer_brewing",
    aliases=(
        "beer_brewing",
        "beer brewing",
        "啤酒酿造",
        "啤酒工艺",
        "brewing science",
        "啤酒工艺学",
        "beer science",
        "啤酒学",
        "酿造工艺",
        "beverage brewing",
        "啤酒酿造工艺",
        "craft brewing",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与工艺/产品问题）",
            "literature review（文献综述）",
            "materials and methods（原料、工艺与实验方法）",
            "results（感官评价与理化指标）",
            "discussion（讨论与工艺优化）",
            "conclusion（结论）",
            "references",
        ),
        "case_study": (
            "abstract",
            "introduction",
            "case description（案例背景）",
            "recipe and brewing（配方与工艺）",
            "sensory evaluation（感官评价）",
            "discussion（反思与改进）",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "main developments（行业/工艺综述）",
            "outlook（趋势展望）",
            "references",
        ),
    },
    citation_style="APA 7（作者-年份；Food Chemistry 遵循 Elsevier 规范）",
    reporting_standards={
        "sensory_analysis": "感官评价遵循 ISO 8586 与 ISO 13299 报告规范",
        "case_study": "案例研究遵循 SAGER 案例报告规范",
        "experimental": "工艺实验遵循预注册与可复现性规范",
        "systematic_review": "系统综述遵循 PRISMA 声明",
    },
    conventions=(
        "配方须同时给出英制与公制用量（L、kg、°C）并标注精度（如 ±0.5 kg）",
        "麦芽/啤酒花须注明品种、产地、批次、α-酸含量与新鲜度",
        "酵母须注明菌株（如 US-05、WLP001）与接种密度",
        "感官评价须报告评价员人数、评价维度（外观、香气、口感、余味）与统计方法",
        "涉及酒精成分与酒精含量的建议须标注法规依据（如美国 TTB、欧盟 2008/12/EC）",
        "禁止以「更好喝」「更健康」等主观断言替代可核验指标",
    ),
    key_venues=(
        "Journal of the Institute of Brewing",
        "BrewingScience",
        "Leavening",
        "Alcohol Science & Research",
        "Alcohol and Alcoholism",
        "Food Chemistry",
        "Journal of Food Science",
        "Brewing Research",
        "Food Research International",
        "Fermentation",
    ),
    units_and_formulas_notes=(
        "体积用 L；质量用 kg；温度用 °C；体积比用 %（v/v）",
        "酒精含量用 ABV%（体积分数）；pH 无量纲；Brix 用 °Brix",
        "麦芽比重用 SG 或 Plato；pH 用无量纲",
        "啤酒花 α-酸含量用 %（w/w）；酒精度用 ABV%",
        "感官评分使用 ISO 标准化的量表（1-9 分或 1-10 分），并注明量表类型",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "艺术作品", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("Beersmith 3", "Brewfather", "Brewlogix", "Brewcraft", "Labcorp Analytical Services", "Alconico Beer Lab", "Brewtech Equipment", "CoolBot Temp Controller", "Fermentis Yeast Database", "Northern Brewer Hops", "Yakima Chief Hops", "Rahr Malting", "Weyermann Malting", "Morey Malting", "Cargill Brewtech", "ISO 1335 Taste Panel", "Maltster's Grist Mill", "Hood Hops Extractor", "Zymatic Brewing System", "BreweryOS Cloud"),
    category="工学",
    databases=("OpenAlex", "CNKI", "万方", "PubMed"),
)
