"""Behavioural sciences 学科论文支持：行为科学/认知行为体裁、APA 引用样式与心理学记法注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="behavioural_sciences",
    aliases=(
        "behavioural_sciences",
        "behavioural science",
        "行为科学",
        "行为心理学",
        "behavioral psychology",
        "行为与心理科学",
        "cognitive behavioral science",
        "cognitive psychology",
        "社会心理学",
        "sociology of behaviour",
        "socio-ecological sciences",
        "behavioral and brain sciences",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与行为问题）",
            "literature review（文献综述）",
            "methods（方法：设计、样本、工具、伦理）",
            "results（结果）",
            "discussion（讨论与理论/应用启示）",
            "conclusion（结论）",
            "references",
        ),
        "laboratory_experiment": (
            "abstract",
            "introduction",
            "design（设计）",
            "procedures（流程）",
            "results（结果）",
            "discussion（讨论）",
            "references",
        ),
        "survey": (
            "abstract",
            "introduction",
            "methods（样本、问卷、施测）",
            "results（结果）",
            "discussion（讨论）",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "main developments（理论综述）",
            "outlook（趋势展望）",
            "references",
        ),
    },
    citation_style="APA 7（作者-年份；Psychological Bulletin 遵循 APA 规范）",
    reporting_standards={
        "experimental": "实验研究遵循 CONSORT 或实验报告规范",
        "survey": "调查研究遵循 AAPOR 报告规范",
        "meta_analysis": "元分析遵循 PRISMA 声明",
        "systematic_review": "系统综述遵循 PRISMA 声明",
        "qualitative": "质性研究遵循 COREQ 或 SRQR",
        "ethics": "人类被试研究遵循 Declaration of Helsinki 与 IRB 审批",
        "preregistration": "预注册须注明（如 OSF、AsPredicted、PsyArXiv）",
    },
    conventions=(
        "研究须报告样本量、年龄、性别、教育水平、社会经济背景",
        "工具/问卷须报告信效度（Cronbach's α、KR-20、CFA 拟合指数）",
        "统计方法须报告检验类型、显著性水平、效应量（如 Cohen's d 或 η²）",
        "预注册须注明平台（如 OSF、AsPredicted、PsyArXiv）",
        "被试知情同意与伦理审批（IRB）须说明",
        "统计结果用 M±SD、CI、p 值，p<.05 视为显著",
        "禁止以「明显」「显著」等模糊词替代可核验的统计指标",
    ),
    key_venues=(
        "Annual Review of Psychology",
        "Journal of Personality and Social Psychology",
        "Psychological Bulletin",
        "Psychological Review",
        "Cognition",
        "Cognitive Psychology",
        "Journal of Experimental Psychology: General",
        "Journal of Experimental Psychology: Learning, Memory, and Cognition",
        "Journal of Experimental Social Psychology",
        "Personality and Social Psychology Review",
    ),
    units_and_formulas_notes=(
        "反应时间用 ms；视觉角度用 °；频率用 Hz",
        "信度用 Cronbach's α、KR-20 或 split-half",
        "效度用 CFA 拟合指数（CFI、TLI、RMSEA、SRMR）",
        "统计量用 t、F、χ²、d、η²、r 或 R²",
        "p 值保留三位小数，p<.001 用 <.001 表示",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "教案与教材", "报告", "数据集"),
    tools=("PsychoPy3", "OpenSesame", "Inquisit (Millisecond)", "E-Prime (Millisecond)", "SPSS 26", "R (psych, lavaan)", "JASP", "Stata 17", "SAS 9.4", "Mplus 8.6", "AMOS", "NVivo 14", "ATLAS.ti", "Dedoose", "MAXQDA", "Qualtrics", "SurveyMonkey", "REDCap", "Open Science Framework (OSF)", "AsPredicted", "Dataverse", "Harvard Dataverse", "OpenICPSR", "G*Power", "Python (NumPy, Pandas)", "Python (statsmodels)", "Python (scikit-learn)", "MATLAB", "R Commander", "Minitab 21"),
    category="理学",
    databases=("OpenAlex", "CNKI", "万方", "Crossref", "Semantic Scholar", "PsyArXiv"),
)
