"""行为经济学学科论文支持：实验/现场/理论体裁、APA 引用样式与社科统计记法注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="behavioral_economics",
    aliases=(
        "behavioral_economics",
        "行为经济学",
        "行为金融",
        "实验经济学",
        "experimental economics",
        "behavioral finance",
        "neuroeconomics",
        "神经经济学",
        "psychology of economics",
        "行为决策",
        "behavioral decision making",
        "行为决策与经济学",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "theory（理论框架）",
            "hypotheses（假设）",
            "experimental design（实验设计）",
            "results（结果）",
            "discussion（讨论）",
            "references",
        ),
        "laboratory_experiment": (
            "abstract",
            "introduction",
            "design（设计）",
            "procedures（流程）",
            "results（结果）",
            "discussion（讨论）",
            "references",
        ),
        "field_experiment": (
            "abstract",
            "introduction",
            "setting（现场）",
            "treatment（处理）",
            "results（结果）",
            "discussion（讨论）",
            "references",
        ),
        "theory": (
            "abstract",
            "introduction",
            "model（模型）",
            "analysis（分析）",
            "implications（含义）",
            "references",
        ),
    },
    citation_style="APA 7（作者-年份；JEB&O 遵循 Elsevier 规范，JoBE 遵循 Springer 规范）",
    reporting_standards={
        "experimental": "实验研究遵循实验报告规范",
        "field_experiment": "现场实验遵循现场实验报告规范",
        "survey": "调查研究遵循 AAPOR 报告规范",
        "meta_analysis": "元分析遵循 PRISMA 声明",
        "systematic_review": "系统综述遵循 PRISMA 声明",
        "preregistration": "预注册须注明",
        "replication": "复现研究遵循 AEA 复现标准",
    },
    conventions=(
        "实验设计与处理须明确",
        "被试招募与报酬须说明",
        "随机化与盲法须报告",
        "假设检验与效应量须给出",
        "预注册须注明（如 AsPredicted、OSF、PsyArXiv）",
        "统计结果须报告 M/SD/SE/CI 与 p 值，效应量用 Cohen's d 或 η²",
        "被试样本量须报告（含被试流失）",
        "金额用统一币种并注明年份",
    ),
    key_venues=(
        "Journal of Economic Behavior & Organization",
        "Journal of Behavioral and Experimental Economics",
        "Journal of Economic Psychology",
        "Experimental Economics",
        "Management Science",
        "American Economic Review",
        "Quarterly Journal of Economics",
        "Econometrica",
        "Journal of the European Economic Association",
        "Games and Economic Behavior",
    ),
    units_and_formulas_notes=(
        "统计量给出 M/SD/SE/CI",
        "效应量用 Cohen's d 或 η²",
        "p 值与显著性须给出",
        "样本量须报告",
        "金额用统一币种并注明年份（如 USD 2023）",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "教案与教材", "报告", "数据集"),
    tools=("z-Tree (University of Cologne)", "oTree (Ortner-Rabinovitz)", "PsychoPy3", "Qualtrics", "SurveyMonkey", "Stata 17", "R (AER, plm, fixest)", "Python (NumPy, Pandas, Pyomo)", "Python (SciPy, statsmodels)", "Python (PyMC, Stan)", "MATLAB", "SPSS 26", "JASP", "SAS 9.4", "Minitab 21", "EViews 13", "Gauss (Apta Labs)", "G*Power", "Open Science Framework (OSF)", "AsPredicted", "OpenICPSR", "Dataverse", "Harvard Dataverse", "World Values Survey (WVS)", "General Social Survey (GSS)", "European Social Survey (ESS)", "American National Election Studies (ANES)", "International Social Survey Program (ISSP)", "OECD Better Life Index", "World Bank Data", "IMF Data", "Bloomberg Data"),
    category="经济学",
    databases=("CNKI", "万方", "OpenAlex", "Crossref", "Semantic Scholar", "PsyArXiv"),
)
