"""生物科学论文支持：多组学整合、模式生物与生物信息学体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="biological_sciences",
    aliases=(
        "biological_sciences",
        "life_sciences",
        "biosciences",
        "molecular_biology",
        "cell_biology",
        "genomics",
        "生物科学",
        "生命科学",
        "分子生物学",
        "细胞生物学",
        "基因组学",
        "系统生物学",
        "生物信息学",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "materials and methods（含数据可用性声明）",
            "results",
            "discussion",
            "acknowledgments",
            "references",
        ),
        "data_paper": (
            "abstract",
            "introduction（数据集背景与动机）",
            "data description",
            "technical validation（质量指标与重复性）",
            "usage notes（许可、访问方式、已知局限）",
            "materials and methods",
            "references",
        ),
        "preprint": (
            "abstract",
            "introduction",
            "results and discussion",
            "methods",
            "data availability and code availability",
            "references",
        ),
    },
    citation_style="ACS 样式或作者-年份（视期刊而定）",
    reporting_standards={
        "genomics": "测序数据遵循 MNase/Hi-C/MAG 标准；提交 GEO/SRA 并报告登录号",
        "protein_data": "结构数据按 PDB/mmCIF 标准提交，含 R-value、完整性与分辨率",
        "cellular_assays": "细胞系须做 STR 鉴定；报告培养基、传代次数与培养条件",
        "animal_experiments": "按 ARRIVE 2.0 报告，含伦理批准号与动物品系",
        "statistics": "报告检验方法、样本量、效应量与多重比较校正方法",
    },
    conventions=(
        "基因符号斜体（如 *BRCA1*），蛋白符号正体（如 BRCA1）；物种缩写遵循 HGNC/UniProt",
        "菌株、细胞系与质粒报告保藏编号（ATCC/DSMZ/加德纳）、来源与鉴定结果",
        "抗体报告厂商、目录号与 RRID；一抗稀释比与孵育时间必须给出",
        "统计描述为 mean ± SD 并给出 n；独立样本量在方法中定义（独立生物样本 vs 重复测量）",
        "图表编号与正文引用一致；多面板图使用 a/b/c 标注并在图注逐一说明",
    ),
    key_venues=(
        "Nature",
        "Science",
        "Cell",
        "Nature Genetics",
        "Cell Reports",
        "Molecular Cell",
        "Current Biology",
        "PNAS",
        "eLife",
    ),
    units_and_formulas_notes=(
        "浓度用 μM/nM 或 mg/mL；分子量用 kDa；温度用 °C；pH 无单位",
        "表达量以 fold change 报告并给出 log2 与 FDR（BH 校正阈值）",
        "测序深度用 reads、×coverage（如 30×）；变异频率用 variant allele frequency",
        "蛋白结合用 Kd（Kd, nM）并标注测定方法（SPR/ITC/EMSA）",
        "细胞存活报告 % viability 或 OD490；EC50/IC50 给出 CI",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("BLAST", "Primer3", "SnapGene", "Benchling", "Vector NTI", "Geneious Prime", "Cytoscape", "Cloudbreak/IGV", "Galaxy Project", "Illumina NovaSeq X", "Oxford Nanopore MinION", "Thermo Fisher QISeq 300", "BD FACSCanto II", "Bio-Rad CFX96", "Thermo Fisher QuantStudio 5", "Zeiss LSM 980", "Nikon A1R", "Olympus IX73", "Beckman Optima L-90K", "Thermo NanoDrop One", "Bio-Tek Cytation 5", "Python（Biopython / Scanpy）", "R", "GraphPad Prism"),
    category="理学",
    databases=("PubMed", "Europe PMC", "GEO", "SRA", "UniProt", "Ensembl", "Zenodo"),
)
