"""生物医学与临床科学论文支持：临床研究、转化医学与循证医学体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="biomedical_and_clinical_sciences",
    aliases=(
        "biomedical_and_clinical_sciences",
        "biomedical_sciences",
        "clinical_research",
        "translational_medicine",
        "evidence_based_medicine",
        "biomedicine",
        "生物医学",
        "临床医学研究",
        "转化医学",
        "循证医学",
        "临床与实验医学",
        "临床流行病学",
    ),
    paper_types={
        "clinical_trial": (
            "abstract",
            "introduction（临床问题、目标与假设）",
            "methods（设计、被试、干预、终点、统计分析计划）",
            "results",
            "discussion（疗效、安全性、与既有研究对比）",
            "acknowledgments and conflicts of interest",
            "references",
        ),
        "diagnostic_accuracy": (
            "abstract",
            "introduction",
            "participants and design",
            "index test and reference standard",
            "results（敏感度、特异度、似然比、ROC）",
            "discussion",
            "references",
        ),
        "meta_analysis": (
            "abstract",
            "introduction",
            "methods（检索策略、纳入排除标准、异质性模型）",
            "results（森林图与偏倚评估）",
            "discussion（证据等级、研究局限、临床意义）",
            "references",
        ),
        "systematic_review": (
            "abstract",
            "introduction",
            "methods（PICO、检索式、PRISMA 流程）",
            "results",
            "discussion（GRADE 证据质量）",
            "references",
        ),
    },
    citation_style="Vancouver（编号，如 [1]）；系统综述常用 AMA 样式",
    reporting_standards={
        "randomized_trial": "随机对照试验按 CONSORT 2010 报告",
        "observational": "观察性研究按 STROBE 报告",
        "diagnostic_study": "诊断准确性研究按 STARD 2015 报告",
        "systematic_review": "系统综述按 PRISMA 2020 报告",
        "protocol": "试验方案按 SPIRIT 报告；注册须给出 ClinicalTrials.gov/NCT 编号",
        "ethical": "伦理批准、知情同意与资助声明须完整报告",
    },
    conventions=(
        "试验编号（NCT）与试验注册信息须出现在标题、摘要与方法中",
        "干预与对照组的纳入/排除标准须显式列表，退出与失访需报告",
        "终点分为主要终点与次要终点，并在统计学部分声明多重比较策略",
        "统计描述区分意向治疗分析（ITT）与符合方案分析（PP）",
        "安全性按 CTCAE 或 WHO 分级报告不良事件，含严重不良事件（SAE）上报",
    ),
    key_venues=(
        "The Lancet",
        "New England Journal of Medicine",
        "JAMA",
        "The BMJ",
        "Annals of Internal Medicine",
        "The Journal of Clinical Investigation",
        "European Heart Journal",
        "Clinical Chemistry",
    ),
    units_and_formulas_notes=(
        "剂量用 mg/kg/d；血药浓度用 mg/L 或 ng/mL；酶活性用 U/L",
        "风险报告用 RR（相对风险）、HR（风险比）、OR（比值比），并给出 95% CI",
        "诊断试验报告敏感度、特异度、阳性/阴性似然比、PPV/NPV 与约登指数",
        "检验水准 α=0.05（双尾），双侧 p 值；生存分析用 Kaplan-Meier + log-rank",
        "剂量-反应关系给出 CIs 并注明剂量单位与暴露时长",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "译文", "报告", "数据集"),
    tools=("SPSS", "SAS", "R", "Stata", "GraphPad Prism", "RevMan Web（Cochrane）", "Epidata 4", "REDCap", "OpenClinica", "Roche cobas c311", "Roche cobas 8000", "Sysmex XN-1000i", "Radiometer ABL800 FLEX", "Mindray CL-6000i", "Siemens SOMATOM go.", "GE SIGNA Premier 3T MRI", "GE Voluson E10", "Olympus VISERA CV-290", "Philips IntelliVue MX750", "Illumina NovaSeq X Plus", "Bio-Rad T1000", "BD FACSCanto II", "Olympus CX31"),
    category="医学",
    databases=("PubMed", "Cochrane Library", "ClinicalTrials.gov", "Europe PMC", "OpenAlex"),
)
