"""生物技术工程论文支持：生物制造、放大工艺、发酵工程与生物反应器体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="biotechnology_engineering",
    aliases=(
        "biotechnology_engineering",
        "bioengineering",
        "biomanufacturing",
        "fermentation_engineering",
        "bioprocess_engineering",
        "生物工程",
        "生物制造",
        "发酵工程",
        "生物过程工程",
        "生物工艺工程",
        "生物反应器工程",
        "生物炼制工程",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "materials and methods（菌种、培养基、发酵条件）",
            "results",
            "discussion",
            "conclusions",
            "references",
        ),
        "process_design": (
            "abstract",
            "introduction",
            "process description（流程、物料与能量衡算）",
            "optimization（DOE、参数敏感性）",
            "scale-up（实验室→中试→生产）",
            "results",
            "conclusions",
            "references",
        ),
        "modeling": (
            "abstract",
            "introduction",
            "model（动力学/代谢流模型）",
            "parameter estimation and validation",
            "sensitivity analysis",
            "discussion",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "technologies",
            "applications",
            "challenges",
            "conclusions",
            "references",
        ),
    },
    citation_style="ACS 样式（上标编号），如 ¹ 或 [1]",
    reporting_standards={
        "genetic_engineering": "基因工程须报告载体图谱、插入片段序列、密码子优化与表达条件",
        "fermentation": "发酵须报告培养基组成、培养条件（温度/pH/溶氧/转速）、发酵罐规格",
        "purification": "纯化须报告步骤、收率、纯度（SDS-PAGE/HPLC）、内毒素水平",
        "bioassay": "生物活性须报告检测方法、IC50/EC50、阳性对照与重复次数",
        "scale_up": "放大须报告容积比、混合时间与传热时间、剪切力与氧传递系数（kLa）",
    },
    conventions=(
        "菌株用标准编号（ATCC/CGMCC/CCTCC）+ 来源",
        "酶用 EC 编号；基因用标准命名（斜体/下划线）",
        "质粒图用标准标注（启动子/选择标记/多克隆位点）",
        "发酵参数用表格汇总；产率用 g/L 或 U/mL",
        "安全性须声明生物安全等级（BSL-1/2/3）",
    ),
    key_venues=(
        "Nature Biotechnology",
        "Metabolic Engineering",
        "Biotechnology and Bioengineering",
        "Biotechnology Advances",
        "Bioresource Technology",
        "Journal of Biotechnology",
        "Bioprocess and Biosystems Engineering",
        "Chemical Engineering Journal",
    ),
    units_and_formulas_notes=(
        "浓度用 mM/μM/mL⁻¹；OD 用 OD600",
        "酶活用 U/mg（比活）或 U/mL",
        "发酵产率用 g/L 或 mol/mol（摩尔转化率）",
        "基因拷贝数用 copies/cell 或 copies/ng DNA",
        "通气量用 vvm；kLa 用 1/h；功率输入用 kW/m³；热量用 kJ/kg",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("Aspen Plus", "Aspen HYSYS", "SimSci PRO-II", "gPROMS", "MATLAB", "Python（numpy / Pyomo）", "COBRA Toolbox（MATLAB）", "Cytoscape", "AutoCAD", "AutoCAD Plant 3D", "SolidWorks", "SmartPlant 3D", "SmartPlant P&ID", "ANSYS Fluent", "ANSYS Mechanical", "COMSOL Multiphysics", "Sartorius Biostat B Plus", "Sartorius Biostat MQ250", "Sartorius MultiQBioractor", "Infors HT Bioflask Shaker", "Thermo Fisher FPG1600", "Thermo Fisher Amicon Ultra", "Cytiva ÄKTA pure 25", "Thermo Scientific V350", "Bio-Rad T100", "Beckman JLA20"),
    category="工学",
    databases=("PubMed", "Europe PMC", "OpenAlex", "Crossref", "Google Patents"),
)
