"""金融学科论文支持：公司金融/投资学/资产定价/计量金融体裁与实证规范。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="business_finance",
    aliases=(
        "business_finance",
        "金融",
        "金融学",
        "公司金融",
        "投资学",
        "商业银行",
        "Financial Economics",
        "Corporate Finance",
        "Investment",
        "Business Finance",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景、动机与问题）",
            "literature review",
            "hypotheses",
            "research design（研究设计）",
            "data（数据与变量）",
            "results（结果）",
            "robustness（稳健性检验）",
            "conclusions",
            "references",
        ),
        "empirical": (
            "abstract",
            "introduction",
            "theoretical framework",
            "sample and data",
            "methodology",
            "results",
            "robustness",
            "conclusion",
            "references",
        ),
        "asset_pricing": (
            "abstract",
            "introduction",
            "model setup",
            "data",
            "analysis",
            "tests（Fama-MacBeth/因子模型检验）",
            "conclusion",
            "references",
        ),
    },
    citation_style="APA 7 或金融领域惯用样式（如 Journal of Finance 的 Journal of Finance Style Guide）",
    reporting_standards={
        "archival": "档案研究须报告样本筛选、缺失处理与变量构造",
        "factor_model": "因子模型须报告因子载荷与载荷检验",
        "portfolio_test": "组合检验须给出分组规则、加权方式与多空 PnL",
        "survey": "调查须报告样本量、抽样与回复率",
    },
    conventions=(
        "数据源须注明来源、下载时间与样本期",
        "变量须给出完整构造过程与描述性统计",
        "资产定价模型须报告因子载荷、IC、t 值与 Newey-West 标准误",
        "组合检验须给出分组规则与调整异常收益（如 HML、UMD）",
        "结果稳健性须覆盖样本期、变量与模型设定三个维度",
    ),
    key_venues=(
        "Journal of Finance",
        "Journal of Financial Economics",
        "Review of Financial Studies",
        "Journal of Banking & Finance",
        "Financial Analysts Journal",
        "Review of Financial Studies",
        "Journal of Financial and Quantitative Analysis",
        "金融研究",
        "经济研究",
        "管理世界",
    ),
    units_and_formulas_notes=(
        "金额以人民币元或统一币种报告并注明年份",
        "收益率以百分比（%）或基点（bp）报告",
        "统计量给出 M/SD/SE/CI",
        "回归系数给出 Newey-West 标准误与显著性",
        "样本量与时间跨度须报告",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "教案与教材", "报告", "数据集"),
    tools=("Bloomberg Terminal", "Wind 万得", "同花顺 iFinD", "东方财富 Choice", "通达信", "Excel（金融建模）", "MATLAB", "Python（pandas/NumPy）", "R（量化分析）", "Stata（面板与事件研究）", "RStudio", "Tableau", "Microsoft Power BI", "Qlik Sense", "QuantLib", "FRED", "LSEG/Refinitiv", "FactSet", "Capital IQ (S&P)", "Alpha Vantage", "TradingView", "Finviz", "Kaggle", "Databricks"),
    category="经济学",
    databases=("CNKI", "万方", "Wind", "iFinD", "OpenAlex", "Crossref", "SSRN"),
)
