"""屠宰学科论文支持：屠宰工艺、肉类加工、HACCP 食品安全与肉质评价体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="butchery",
    aliases=(
        "butchery",
        "屠宰",
        "屠宰学",
        "肉类加工",
        "畜牧屠宰",
        "屠宰技术",
        "Meat Processing",
        "Meat Production",
        "Slaughter",
        "Butchery and Meat Processing",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景与问题）",
            "literature review",
            "material and methods（材料与工艺）",
            "results",
            "discussion",
            "conclusion",
            "references",
        ),
        "food_science": (
            "abstract",
            "introduction",
            "materials",
            "methods（物理/化学/微生物检测）",
            "results",
            "discussion",
            "conclusion",
            "references",
        ),
        "process_optimization": (
            "abstract",
            "introduction",
            "process description（工艺流程）",
            "experimental design（DOE/正交试验）",
            "results",
            "optimization（工艺优化）",
            "conclusion",
            "references",
        ),
    },
    citation_style="APA 7 或 GB/T 7714；肉类期刊多采用 Elsevier 期刊体例",
    reporting_standards={
        "haccp": "HACCP 研究须报告危害分析、CCP、关键限值、监控与纠偏",
        "microbial": "微生物研究须报告培养条件、菌种、计数方法（CFU/mL 或 CFU/g）",
        "sensory": "感官评价须报告评价员人数、培训、评分尺度与统计分析",
        "traceability": "追溯研究须说明批次、时间戳与数据来源",
    },
    conventions=(
        "温度单位用摄氏度（°C），时间用秒（s）或分钟（min）",
        "HACCP 计划须覆盖 7 大原理并给出关键限值（CL）与关键限值监控",
        "理化指标须注明来源方法（如 AOAC、GB 方法）",
        "批次编号须给出可追溯路径",
    ),
    key_venues=(
        "Meat Science",
        "Meat Research",
        "Journal of Food Science",
        "LWT - Food Science and Technology",
        "Food Control",
        "Journal of Food Protection",
        "International Journal of Food Microbiology",
        "Food Research International",
        "肉类研究",
        "食品科学",
        "中国食品添加剂",
    ),
    units_and_formulas_notes=(
        "温度以 °C 报告，湿度以 %RH 报告",
        "含水量、pH 等须注明检测方法与误差",
        "微生物计数以 CFU/mL 或 CFU/g 报告",
        "水分活度以 a_w 报告（3 位小数）",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("SafeTrix HACCP 管理软件", "eHACCP", "FoodLogix", "TraceabilityPro", "GEA Farm Technologies 屠宰流水线", "Hormann 制冷设备", "肉类分割带锯（Band Saw）", "真空包装机（Hass 品牌）", "X 射线异物检测机（Bosch Security）", "金属探测器（Metall detection）", "Hanna 数字温度计", "Mettler-Toledo pH 计", "Konica Minolta 色差仪", "Sartorius 水分测定仪", "Leica 生物显微镜", "Spectro 活体检测", "电子秤（Mettler Toledo）", "TraceScan（电子追溯系统）", "Microsoft Excel", "SPSS", "Minitab", "R", "Python（Pandas/SciPy）", "LaTeX", "EndNote"),
    category="农学",
    databases=("CNKI", "万方", "OpenAlex", "Crossref", "ScienceDirect"),
)
