"""买卖学科论文支持：贸易/零售/采购/跨境电商体裁与实证规范。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="buying_and_selling",
    aliases=(
        "buying_and_selling",
        "买卖",
        "贸易",
        "商贸",
        "零售",
        "电子商务",
        "采购",
        "Buying and Selling",
        "Trade",
        "Commerce",
        "Retailing",
        "Procurement",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（背景与问题）",
            "literature review",
            "hypotheses",
            "research design",
            "data",
            "results",
            "discussion",
            "conclusion",
            "references",
        ),
        "case_study": (
            "abstract",
            "introduction",
            "case background",
            "research design",
            "findings",
            "discussion",
            "conclusion",
            "references",
        ),
        "empirical": (
            "abstract",
            "introduction",
            "theoretical framework",
            "sample and data",
            "methodology",
            "results",
            "robustness",
            "conclusion",
            "references",
        ),
    },
    citation_style="APA 7；贸易类期刊遵循 Journal of International Business Studies 体例",
    reporting_standards={
        "archival": "档案/交易数据须说明数据源、样本期与清洗规则",
        "survey": "调查须报告样本量、抽样与回复率",
        "experimental": "实验/因果推断须报告随机化与效应量",
    },
    conventions=(
        "交易金额须注明币种与年份",
        "跨境贸易须说明贸易术语（Incoterms 2020）与物流方式",
        "零售研究须报告门店数、样本量与区域覆盖",
        "电子商务研究须说明数据来源（平台 API/爬虫）与合规性",
    ),
    key_venues=(
        "Journal of International Business Studies",
        "Journal of Marketing",
        "Journal of International Marketing",
        "Journal of Retailing and Consumer Services",
        "Journal of Supply Chain Management",
        "Journal of Purchasing and Materials Management",
        "International Journal of Electronic Commerce",
        "管理世界",
        "中国工业经济",
        "国际贸易问题",
        "商业经济研究",
    ),
    units_and_formulas_notes=(
        "金额以人民币元或统一币种报告并注明年份",
        "增长率以百分比（%）报告",
        "样本量与时间跨度须报告",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "教案与教材", "报告", "数据集"),
    tools=("阿里巴巴 1688", "阿里巴巴国际站 Alibaba.com", "亚马逊卖家中心 Amazon Seller Central", "中国制造网 Made-in-China.com", "慧聪网", "Shopee", "天猫", "京东", "eBay", "Etsy", "Shopify", "WooCommerce", "Magento", "TradeKey", "DHL", "FedEx", "UPS", "SAP Ariba", "Coupa", "Icertis", "中国国际贸易单一窗口", "Protrade", "Microsoft Excel", "SPSS", "Stata", "Python（Pandas）"),
    category="管理学",
    databases=("CNKI", "万方", "OpenAlex", "Crossref", "JSTOR"),
)
