"""Civil engineering 学科论文支持：结构设计/施工/交通/水利/岩土/基础设施安全。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="civil_engineering",
    aliases=(
        "Civil engineering", "civil", "structural engineering",
        "geotechnical engineering", "transportation engineering",
        "hydraulic engineering", "construction engineering",
        "土木工程", "结构工程", "岩土工程", "桥梁工程", "水利工程", "交通工程",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "literature_review",
            "methodology",
            "results",
            "discussion",
            "conclusion",
            "references",
        ),
        "case_study": (
            "abstract",
            "introduction",
            "project_background",
            "analysis",
            "findings",
            "lessons_learned",
            "references",
        ),
        "design": (
            "abstract",
            "design_criteria",
            "analysis",
            "calculations",
            "detailing",
            "review",
            "references",
        ),
        "experimental": (
            "abstract",
            "introduction",
            "specimen_and_material",
            "experimental_setup",
            "results",
            "finite_element_verification",
            "references",
        ),
    },
    citation_style="ASCE 样式（American Society of Civil Engineers；国内期刊遵循 GB/T 7714）",
    reporting_standards={
        "design_code": "采用的规范（ACI 318 / AISC 360 / AS 3600 / GB 50010 / GB 50011 / EN 199）与版本须写明",
        "load": "荷载组合（恒/活/风/地震/温度）与安全系数须列出",
        "material": "强度报告用标准试件、龄期、养护条件；材料参数须注明来源",
        "test": "试验装置、加载制度、位移/应变测点布置与数据采集频率须描述",
        "safety": "可靠性指标 β 与目标失效概率须给出；分项系数说明",
        "finite_element": "有限元报告网格独立性分析、边界条件、接触/本构模型与软件版本",
        "uncertainty": "随机变量分布、协方差与蒙特卡洛样本量须说明",
    },
    conventions=(
        "单位 SI 为主（kN、MPa、mm、°C）；美国单位用 ft/kip/ksi 需注明",
        "截面图、配筋图按制图标准；钢筋直径用 φ 前缀；钢构件用规格（如 H400×200×8×13）",
        "有限元网格收敛分析报告；边界条件与接触假定提及",
        "误差与破坏模式用照片+简图；破坏准则给出（CCFT/Mohr-Coulomb/Drucker-Prager 等）",
        "地震工程给出地震动参数（PGA、Sa(T)、频谱加速度）、设防烈度与设计地震分组",
        "规范公式引用编号与版本；符号含义首现定义",
    ),
    key_venues=(
        "Journal of Structural Engineering",
        "Engineering Structures",
        "Journal of Construction Engineering and Management",
        "Journal of Geotechnical and Geoenvironmental Engineering",
        "Journal of Hydraulic Engineering",
        "ASCE Journal of Bridge Engineering",
        "ACI Structural Journal",
        "Earthquake Engineering & Structural Dynamics",
        "Construction & Building Materials",
        "土木建筑与环境工程",
    ),
    units_and_formulas_notes=(
        "承载力 kN；变形 mm；应力 MPa；应变 %；轴压比 n",
        "刚度 kN·m²；延性系数 μ；耗能能力 kJ；周期 s",
        "地震动：加速度 g 或 m/s²；谱加速度 Sa(T, η) 给出周期 T 与阻尼比 η",
        "土体：含水量 w（%）、孔隙比 e、干密度 ρd（g/cm³）、抗剪参数 c、φ",
        "水工/输水：流量 Q m³/s、水头 H m、流速 v m/s",
        "规范公式引用编号，符号含义首现定义",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("AutoCAD Civil 3D", "Autodesk Revit", "Autodesk Infrastructure Design (C3D)", "Autodesk Robot Structural Analysis", "SAP2000", "MIDAS Civil", "MIDAS Gen", "STAAD.Pro", "ETABS", "SACS (Ship & Offshore)", "SAFE (slab foundation)", "SpaceGAS", "CSI Bridge", "LUSAS", "SCIA Engineer", "ANSYS Mechanical", "ABAQUS", "Nastran", "SOLIDWORKS Simulation", "SOLIDWORKS", "Catia", "OpenSees", "OpenFOAM", "LS-DYNA", "FLAC3D", "PLAXIS 2D/3D", "GeoStudio", "ROCKLAB", "RocScience Slide", "RocSlide", "UDEC", "3DEC", "SWMM (Storm Water Management Model)", "HEC-RAS", "HEC-HMS", "HEC-HSS", "Sedimentation Transport Model", "MOSICE", "SWAT", "MIKE 11", "MIKE 21", "WASP", "HEC-View", "Civil 3D AutoBuild", "Trimble StreetGauge", "Trimble Business Center", "Leica Cyclone", "Trimble TerraSolid", "CASS", "MapGIS", "ArcGIS Pro", "QGIS", "Navisworks", "InfraWorks", "Revit MEP", "Primavera P6", "Microsoft Project", "Oracle P6", "Bentley OpenBuildings", "Bentley OpenRoads", "Bentley OpenRail", "Bentley MicroStation", "Dialux", "EPIC", "FIDIS", "MATLAB", "Python (NumPy/SciPy)", "COMSOL Multiphysics", "MATPOWER"),
    category="工学",
    databases=("OpenAlex", "Crossref", "CNKI", "Scopus", "Web of Science"),
)
