"""控制工程·机械电子与机器人学科论文支持：机器人、机械电子集成、感知与控制一体化。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="control_engineering_mechatronics_and_robotics",
    aliases=(
        "mechatronics",
        "robotics",
        "robot engineering",
        "机械电子工程",
        "控制工程",
        "机器人学",
        "mechatronics and robotics",
        "robot systems",
        "工业机器人",
        "industrial robotics",
        "intelligent robotics",
        "智能机器人",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（工程背景与机器人系统动机）",
            "system architecture（系统架构：感知-规划-控制-执行）",
            "kinematics and dynamics（运动学与动力学建模）",
            "control design（控制器设计与参数整定）",
            "simulation and experiment（仿真与实物验证）",
            "performance evaluation",
            "conclusions",
            "references",
        ),
        "design_report": (
            "abstract",
            "requirements（任务与工况）",
            "design development（方案对比与优化）",
            "structural/mechanical analysis（有限元/静强度/疲劳）",
            "control validation",
            "references",
        ),
        "case_study": (
            "abstract",
            "task description",
            "system configuration",
            "results",
            "lessons learned",
            "references",
        ),
        "review": (
            "abstract",
            "historical overview",
            "current methods",
            "open challenges",
            "references",
        ),
    },
    citation_style="IEEE 样式（编号），机器人会议与期刊通用",
    reporting_standards={
        "kinematics": "运动学须报告正/逆解方法、工作空间与奇异性分析",
        "dynamics": "动力学须报告模型（Newton-Euler/Lagrangian）与参数辨识方法",
        "controller": "控制器类型（PD/IMP/RL/OSC）与增益须完整报告",
        "experiment": "实验环境（温度、精度、传感器）须披露",
        "metrics": "性能指标（精度、速度、能耗、成功率）须报告",
        "safety": "涉及安全须遵循 ISO 10218 / ISO 13849 或 GB/T 11291",
        "standards": "引用标准须标注 ISO / ANSI / GB 编号",
    },
    conventions=(
        "遵循 ROS/ROS 2 通信规范（DDS、Topic/Service/Action）",
        "机器人描述遵循 URDF/XRDF 标准",
        "运动学遵循 DH 参数化（Modified DH 优先）",
        "动力学遵循 Lagrangian 或 Newton-Euler 方法",
        "安全标准按 ISO 10218 / ISO 13849 或 GB/T 11291 定级",
        "实验数据须含时间序列、初值与误差分析",
    ),
    key_venues=(
        "IEEE Transactions on Robotics",
        "IEEE Robotics and Automation Letters (RA-L)",
        "IEEE Transactions on Industrial Electronics",
        "IEEE Transactions on Automation Science and Engineering",
        "International Journal of Robotics Research (IJRR)",
        "Autonomous Robots",
        "Robotics and Computer-Integrated Manufacturing (RCIM)",
        "Robotics and Autonomous Systems",
        "Mechatronics",
        "机器人技术与应用",
        "自动化学报",
        "中国机械工程",
        "机械工程学报",
        "控制与决策",
    ),
    units_and_formulas_notes=(
        "长度 m 或 mm；力 N；力矩 N·m",
        "角速度 rad/s；线速度 m/s",
        "关节位置 deg 或 rad；位置精度 mm 或 μm",
        "时间 s；频率 Hz",
        "传感器噪声用 σ 或 3σ",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("ROS", "ROS 2", "Gazebo", "Gazebo Classic", "Gazebo Sim (Ignition)", "NVIDIA Isaac Sim", "MuJoCo", "Bullet", "PyBullet", "OpenAI Gym", "OpenAI Gymnasium", "NVIDIA Isaac Lab", "Webots", "CoppeliaSim (V-REP)", "KUKA RoboGuidance", "Fanuc Roboguide", "ABB RobotStudio", "Universal Robots", "Universal Robots UR5", "Universal Robots UR3", "Universal Robots UR10", "KUKA KR", "Fanuc R-2000iC", "Fanuc R-2000iB", "Fanuc ArcMate", "ABB IRB 6700", "ABB IRB 1200", "ABB IRB 6720", "Kawasaki DUO", "Mitsubishi RV-M", "Yaskawa MOTOMAN", "Yaskawa ARC", "Yaskawa SUMITOMO", "KUKA KRC", "KUKA KRL", "KUKA KMS", "KUKA KSS", "Universal Robots UR-RTDE", "Universal Robots UR-Controlled", "Universal Robots UR-Motion", "Universal Robots UR-Program", "MoveIt", "MoveIt 2", "MoveIt Motion Planner", "MoveIt TF", "OpenCV", "Open3D", "PCL", "MoveIt Servo", "MoveIt Visualize", "MoveIt Setup Assistant"),
    category="工学",
    databases=("arXiv", "OpenAlex", "Crossref", "IEEE Xplore", "CNKI", "Zenodo", "GitHub", "HAL"),
)
