"""起重运输作业（塔吊/汽车吊司机 + 重卡驾驶员）学科论文支持：吊装计算、车辆动力学与司机培训评价体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="crane_and_truck_driving",
    aliases=(
        "crane and truck driving",
        "起重运输",
        "吊车司机",
        "汽车吊司机",
        "重卡驾驶",
        "重型运输",
        "heavy truck driving",
        "crane operation",
        "truck driving",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "materials and methods（设备/路线/司机样本）",
            "results",
            "discussion",
            "conclusions",
            "references",
        ),
        "field_trial": (
            "abstract",
            "introduction",
            "site description（工地/路段/载荷工况）",
            "experimental design",
            "results（载荷/油耗/磨损/事故）",
            "conclusions",
            "references",
        ),
        "training_evaluation": (
            "abstract",
            "introduction",
            "curriculum（大纲与学时）",
            "implementation",
            "assessment（考核与通过率）",
            "conclusions",
            "references",
        ),
        "safety_case": (
            "abstract",
            "incident description",
            "investigation method",
            "root cause analysis",
            "countermeasures",
            "conclusions",
            "references",
        ),
    },
    citation_style="APA 7",
    reporting_standards={
        "load": "起重量、幅度、吊高与工况须完整给出；超载试验注明试验载荷与安全系数",
        "driver": "司机资格（操作证/驾驶证）、工龄与持证类别须报告",
        "safety": "事故率与未遂事件按小时/吨/万公里归一化",
        "fuel": "油耗按 L/100 km 或 L/t·km 报告，注明载重与路况",
        "tire": "轮胎磨损/制动效能须给出测量方法与里程",
    },
    conventions=(
        "吊装载荷按吨（t）计；力矩按 kN·m；幅度按 m；吊高按 m",
        "设备名称给制造商型号与出厂编号；起重机铭牌参数须逐条核对",
        "司机姓名须匿名化（编号 S-01）；事故时间用 24 小时制",
        "工况分为空载/额定/超载，超载工况须在许可试验载荷内并注明安全系数",
        "统计结果报告均值与标准差，显著性检验注明方法与自由度",
        "引用国标用 GB/T 编号（如 GB/T 6067.1、GB 7258、GB 38900）",
    ),
    key_venues=(
        "Journal of Constructional Steel Research",
        "International Journal of Heavy Equipment Engineering and Technology",
        "Journal of Loss Prevention in the Process Industries",
        "Construction, Innovation and Knowledge",
        "Journal of Transportation Safety and Security",
        "Transportation Research Record",
        "Journal of Construction Engineering and Management",
        "Accident Analysis & Prevention",
        "Journal of Safety Research",
        "International Journal of Vehicle Design",
    ),
    units_and_formulas_notes=(
        "吊装载荷 P 与幅度 R 满足额定力矩 M = P·R；试验载荷不超过 110% 额定",
        "油耗按 L/100 km（载重运输）或 L/t·km（运输作业强度）报告",
        "轮胎磨损按 km 与花纹深度 mm 报告；制动效能按制动力总和/车重比报告",
        "单位用 SI；温度、压力、时间统一到国际单位制",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "艺术作品", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("SimuCrane Crane Simulator", "Caterpillar Crane Simulator", "Hoffmann Group Simulator HOS", "Volvo Truck Driving Simulator", "Caterpillar Simulator Solutions", "Heavy Duty Driving Simulator HDS", "Caterpillar C240 Crane", "Liebherr LTM 11000", "Liebherr LTM 1200", "Konecranes Crane Load Moment Indicator LMI", "MammothLift LMI", "Caterpillar Vision Track Monitoring System", "Trimble FleetVision", "Samsara Fleet Management", "Geotab GO", "Petrock V240 Tachograph", "ABD Systems In-Cab Recorder", "Schaeffler Torque Analyzer", "Brammer Clark Tire Pressure Monitoring System", "Bosch TPMS", "Luffing Jib Load Calculator", "Cranes Pro Load Rating Application", "LoadCalc Crane Software", "CraneSafe LMI Software", "KUKA KR360 Robot", "MATLAB", "Origin", "SPSS", "R", "ANSYS Mechanical", "SolidWorks Simulation"),
    category="工学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "OSHA Statistics", "Fleet Management Data"),
)
