"""创意与表演艺术学科论文支持：创作研究、展演报告与实践性论文体裁、芝加哥样式注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="creative_and_performance_art",
    aliases=(
        "creative and performance art",
        "创意与表演艺术",
        "创意艺术",
        "表演艺术",
        "舞蹈与音乐",
        "戏剧与舞台",
        "creative arts",
        "performance arts",
        "dance",
        "music performance",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "literature review",
            "methodology",
            "analysis",
            "discussion",
            "conclusions",
            "references",
        ),
        "practice_based": (
            "abstract",
            "introduction",
            "context（创作背景与问题）",
            "creative process（创作过程）",
            "the work（作品）",
            "performance（展演）",
            "reflection（反思）",
            "conclusions",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope",
            "synthesis",
            "open questions",
            "references",
        ),
    },
    citation_style="Chicago (Notes & Bibliography)",
    reporting_standards={
        "performance": "演出时间、地点、时长、观众数须报告",
        "creativity": "创作过程须描述迭代次数与决策依据",
        "audience": "观众反馈量表信效度须报告",
        "ethics": "人类受试者研究须伦理审查与知情同意",
    },
    conventions=(
        "作品名称首现给出创作年份与媒介；剧本/乐谱/影像以脚注标注",
        "表演日期与时长、场地与观众规模须给出",
        "创作过程与最终作品须区分，草稿与终稿版本标注",
        "引用艺术家与理论家时用姓名首字母缩写或规范简称",
        "术语按芝加哥手册统一，不混用中英混排",
    ),
    key_venues=(
        "Journal of Aesthetics and Art Criticism",
        "Performance Research",
        "PAJ: A Journal of Performance and Visual Arts",
        "Theatre Research International",
        "Journal of Music Theory",
        "Musicology",
        "Dance Research Journal",
        "Theatre Journal",
        "Journal of the Society for Theatre Research",
        "Studies in Dance and Movement",
        "Contemporary Literature Review",
        "Performance Arts & Culture",
    ),
    units_and_formulas_notes=(
        "演出时长用分钟；观众规模用人；曲目/场次给出编号",
        "乐谱/剧本引用给出版信息（版本、页码或分钟秒）",
        "时间统一为分钟或分钟秒格式，不混用",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "文学作品", "艺术作品", "教案与教材", "译文", "报告", "数据集"),
    tools=("Adobe Creative Cloud", "Adobe Premiere Pro", "Adobe Photoshop", "Adobe After Effects", "Pro Tools", "Logic Pro", "Ableton Live", "FL Studio", "Blender", "Autodesk Maya", "Cinema 4D", "Unreal Engine", "DaVinci Resolve", "Final Cut Pro", "Scrivener", "Notion", "Obsidian", "ProPresenter", "MA Lighting GrandMA3", "ETC Eos", "QLAC QLab", "d&b Soundscape", "DiGiCo SD12", "ZBrush", "Substance Painter", "Houdini", "Sibelius", "MuseScore", "Finale", "GarageBand", "Camtasia", "OBS Studio", "Zoom", "Figma", "Canva", "TikTok", "Instagram", "YouTube"),
    category="艺术学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "MLA International Bibliography"),
)
