"""创意艺术与写作学科论文支持：创作/教学/批评/译作/艺术分析多种体裁、MLA 样式与人文学科注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="creative_arts_and_writing",
    aliases=(
        "creative arts and writing",
        "创意艺术与写作",
        "创意写作",
        "创作学",
        "写作学",
        "creative arts",
        "writing studies",
        "文学创作",
        "写作研究",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（问题与背景）",
            "literature review（文献综述）",
            "analysis（分析）",
            "discussion（讨论）",
            "conclusions（结论）",
            "references",
        ),
        "practice_based": (
            "abstract",
            "introduction",
            "creative process（创作过程）",
            "work（作品）",
            "reflection（反思）",
            "conclusions（结论）",
            "references",
        ),
        "pedagogical_study": (
            "abstract",
            "introduction",
            "course design（课程设计）",
            "implementation（实施）",
            "evaluation（评估）",
            "discussion（讨论）",
            "references",
        ),
        "criticism": (
            "abstract",
            "introduction",
            "theoretical framework",
            "close reading",
            "interpretation",
            "conclusion",
            "references",
        ),
        "translation": (
            "abstract",
            "introduction",
            "source analysis",
            "translation strategy",
            "translation",
            "postscript",
            "references",
        ),
    },
    citation_style="MLA 样式（作者-页码；New Writing 遵循 MLA 规范）",
    reporting_standards={
        "practice": "实践研究遵循创作实践报告规范",
        "pedagogical": "教学研究遵循教学研究报告规范",
        "qualitative": "质性研究遵循 COREQ/SRQR 报告规范",
        "survey": "调查研究遵循 AAPOR 报告规范",
        "systematic_review": "系统综述遵循 PRISMA 声明",
    },
    conventions=(
        "作品与创作过程须区分，创作手记不替代论证明词",
        "教学设计与评估须说明评估工具与评分标准",
        "引文给出页码；版本与版次须注明",
        "理论框架须明确；反思性结论须讨论其限度",
        "作品版本号与提交稿日期须标注",
        "字数用字/词计数并说明计数口径",
    ),
    key_venues=(
        "New Writing",
        "Journal of Creative Writing Studies",
        "TEXT: Journal of Writing and Writing Courses",
        "Creative Writing: Teaching Theory & Practice",
        "Writing in Practice",
        "Journal of Writing Research",
        "Contemporary Literature",
        "PMLA",
        "The Review of English Studies",
        "Comparative Literature",
        "Poetics Today",
    ),
    units_and_formulas_notes=(
        "引文给出页码",
        "版本与版次须注明",
        "字数用字/词计数",
        "时间用统一格式",
        "百分比给出基数",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "文学作品", "艺术作品", "教案与教材", "译文", "报告", "数据集"),
    tools=("Scrivener", "Microsoft Word", "Google Docs", "LaTeX", "Overleaf", "Zotero", "Mendeley", "NVivo", "ATLAS.ti", "MAXQDA", "Adobe InDesign", "Adobe Acrobat", "Adobe Photoshop", "Canva", "ProWritingAid", "Grammarly", "Hemingway Editor", "MWriter", "Ulysses", "iA Writer", "Obsidian", "Notion", "LanguageTool", "Turnitin", "iThenticate"),
    category="文学",
    databases=("CNKI", "万方", "OpenAlex", "Crossref", "MLA International Bibliography"),
)
