"""创意写作学科论文支持：创作/教学/批评/译作体裁、MLA 引用样式与人文学科注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="creative_writing",
    aliases=(
        "creative_writing",
        "creative writing",
        "创意写作",
        "创作学",
        "写作学",
        "写作研究",
        "writing studies",
        "文学创作",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction（问题与背景）",
            "literature review（文献综述）",
            "analysis（分析）",
            "discussion（讨论）",
            "conclusions（结论）",
            "references",
        ),
        "practice_based": (
            "abstract",
            "introduction",
            "creative process（创作过程）",
            "work（作品）",
            "reflection（反思）",
            "conclusions（结论）",
            "references",
        ),
        "pedagogical_study": (
            "abstract",
            "introduction",
            "course design（课程设计）",
            "implementation（实施）",
            "evaluation（评估）",
            "discussion（讨论）",
            "references",
        ),
        "criticism": (
            "abstract",
            "introduction",
            "theoretical framework",
            "close reading",
            "interpretation",
            "conclusion",
            "references",
        ),
        "translation": (
            "abstract",
            "introduction",
            "source analysis",
            "translation strategy",
            "translation",
            "postscript",
            "references",
        ),
    },
    citation_style="MLA 样式（作者-页码；New Writing 遵循 MLA 规范）",
    reporting_standards={
        "practice": "实践研究遵循创作实践报告规范",
        "pedagogical": "教学研究遵循教学研究报告规范",
        "qualitative": "质性研究遵循 COREQ/SRQR 报告规范",
        "survey": "调查研究遵循 AAPOR 报告规范",
        "systematic_review": "系统综述遵循 PRISMA 声明",
    },
    conventions=(
        "作品与创作过程须区分，创作手记不替代论证明词",
        "教学设计与评估须说明评估工具与评分标准",
        "引文给出页码；版本与版次须注明",
        "理论框架须明确；反思性结论须讨论其限度",
        "作品版本号与提交稿日期须标注",
        "字数用字/词计数并说明计数口径",
    ),
    key_venues=(
        "New Writing",
        "Journal of Creative Writing Studies",
        "TEXT: Journal of Writing and Writing Courses",
        "Creative Writing: Teaching Theory & Practice",
        "Writing in Practice",
        "Journal of Writing Research",
        "Contemporary Literature",
        "PMLA",
        "The Review of English Studies",
        "Poetics Today",
    ),
    units_and_formulas_notes=(
        "引文给出页码",
        "版本与版次须注明",
        "字数用 字/词 计数",
        "时间用统一格式",
        "百分比给出基数",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "文学作品", "艺术作品", "教案与教材", "译文", "报告", "数据集"),
    tools=("Scrivener 长文写作管理", "Microsoft Word 文稿编辑", "Google Docs 协作写作", "LaTeX 作品排版", "Overleaf 在线 LaTeX", "Zotero 文献管理", "Mendeley 文献管理", "NVivo 创作过程质性编码", "ATLAS.ti 质性文本分析", "MAXQDA 质性研究分析", "Adobe InDesign 作品集排版", "Adobe Acrobat 书稿审校", "Adobe Photoshop 插图处理", "Canva 封面与装帧设计", "ProWritingAid 文风诊断", "Grammarly 语法检查", "Hemingway Editor 可读性分析", "MWriter 极简写作", "Ulysses 章节写作", "iA Writer 写作环境", "Obsidian 笔记与素材库", "Notion 项目与流程管理", "LanguageTool 多语言校对", "Turnitin 查重", "iThenticate 学术查重"),
    category="文学",
    databases=("CNKI", "万方", "OpenAlex", "Crossref", "MLA International Bibliography"),
)
