"""刑事司法研究学科论文支持：警务/监狱矫正/司法改革/被害人学/法律实证研究体裁、APA 样式注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="criminal_justice_studies",
    aliases=(
        "criminal justice studies",
        "刑事司法研究",
        "刑事司法",
        "司法学",
        "police science",
        "corrections",
        "被害人学",
        "victims of crime",
        "法律实证研究",
        "刑事政策",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "literature review",
            "methods",
            "results",
            "discussion",
            "conclusions",
            "references",
        ),
        "policy": (
            "abstract",
            "introduction",
            "problem statement",
            "policy analysis",
            "implementation",
            "evaluation",
            "conclusions",
            "references",
        ),
        "comparative": (
            "abstract",
            "introduction",
            "conceptual framework",
            "case selection",
            "analysis",
            "findings",
            "discussion",
            "conclusions",
            "references",
        ),
        "practitioner_report": (
            "abstract",
            "background",
            "operational data",
            "analysis",
            "recommendations",
            "references",
        ),
    },
    citation_style="APA 7（括号），如 (Author, Year)",
    reporting_standards={
        "survey": "问卷调查须报告样本量、抽样方法、响应率与量表信效度",
        "administrative_data": "官方数据须报告来源机构、时间范围与分类口径（UCR/NIBRS/ICD-10-CM）",
        "qualitative": "质性研究须报告访谈/观察时长、转录方法、编码过程与三角验证",
        "experimental": "执法干预试验须说明单位、处理组分配、随访周期与流失率",
        "ethics": "敏感数据须经伦理审查，被害人/在押人员信息须匿名化",
    },
    conventions=(
        "犯罪类别与执法数据须用标准分类（UCR/NIBRS/ICD-10-CM）",
        "犯罪率按 per 100,000 population 报告并给出分母口径",
        "统计须报告效应量与置信区间，不得仅报 p 值",
        "地名与机构首次出现用全称，可在文中标注缩写",
        "案例与受害人信息匿名化；涉及在押人员研究须附伦理审查声明",
        "地图须含比例尺、指北针与数据来源；时间序列注明数据年度",
    ),
    key_venues=(
        "Crime, Law and Social Change",
        "Criminal Justice Review",
        "Journal of Police and Criminal Psychology",
        "Journal of Criminal Justice",
        "Journal of Police, Criminal Justice and Corrections",
        "Crime, Victims and Justice",
        "Journal of Corrections",
        "Police Quarterly",
        "Justice Quarterly",
        "Criminology and Public Policy",
        "Criminal Justice Policy Review",
        "Law and Society Review",
    ),
    units_and_formulas_notes=(
        "犯罪率 per 100,000；监禁率 per 100,000；再犯率 %",
        "时间序列用月/年数据；横截面用城市/国家层级",
        "效应量用 Cohen's d / odds ratio；显著性水平注明",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "教案与教材", "报告", "数据集"),
    tools=("Stata", "R", "RStudio", "Python", "SPSS", "NVivo", "ATLAS.ti", "MAXQDA", "Mplus", "SAS", "JASP", "Archi", "ArcGIS", "QGIS", "CrimeStat", "PredPol Analytic", "Policymap", "Tableau", "Power BI", "Microsoft Excel", "UCR / NIBRS Data Access Tool", "Bureau of Justice Statistics DataTool", "ICPSR Dataverse", "FBI Crime Data Explorer", "Europol Crime Statistics", "NCVS Data Tool", "RedCap", "Qualtrics", "Weaviate", "Git", "Obsidian"),
    category="法学",
    databases=("CNKI", "万方", "OpenAlex", "Crossref", "SSRN", "ICPSR", "Bureau of Justice Statistics"),
)
