"""危机支持学科论文支持：危机干预、自杀预防、灾害心理援助、紧急心理支持与创伤研究。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="crisis_support",
    aliases=(
        "crisis support",
        "危机支持",
        "危机干预",
        "crisis intervention",
        "自杀预防",
        "suicide prevention",
        "灾难心理援助",
        "trauma support",
        "紧急心理服务",
        "mental health crisis",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "literature review",
            "methods",
            "results",
            "discussion",
            "conclusions",
            "references",
        ),
        "intervention": (
            "abstract",
            "introduction",
            "intervention design（干预设计）",
            "implementation（实施）",
            "outcomes（基线-随访）",
            "safety monitoring（安全监测）",
            "conclusions",
            "references",
        ),
        "qualitative": (
            "abstract",
            "introduction",
            "context",
            "methodology",
            "findings",
            "discussion",
            "references",
        ),
        "program_evaluation": (
            "abstract",
            "program background",
            "logic model",
            "evaluation design",
            "results",
            "recommendations",
            "references",
        ),
        "case_report": (
            "abstract",
            "case description",
            "assessment",
            "intervention process",
            "outcome",
            "discussion",
            "references",
        ),
    },
    citation_style="APA 7",
    reporting_standards={
        "scale": "量表须报告版本、语言版本与信效度（α/ICC）",
        "case": "个案报告须匿名化并附知情同意",
        "ethics": "涉及自杀意念与创伤数据的研究须经伦理审查",
        "safety": "评估工具须报告阳性筛查后的处置路径",
        "follow_up": "随访周期与失访率须报告",
        "dissemination": "危机术语须避免诱导性表述",
    },
    conventions=(
        "自杀风险分级术语须统一（低/中/高/极高，注明分级标准来源）",
        "量表名称首现给全称与英文缩写，并注明语言版本",
        "个案与研究对象信息须匿名化（编号 C-01），不得出现可识别信息",
        "疗效结果报告效应量与置信区间，不得仅报 p 值",
        "自杀相关表述须使用尊重性语言，避免浪漫化或诱导性描述",
        "须附危机资源/热线信息与数据来源说明",
    ),
    key_venues=(
        "Suicide and Life-Threatening Behavior",
        "Crisis",
        "Crisis Intervention and Suicide Prevention Journal",
        "Emergency Mental Health",
        "Social Psychiatry and Psychiatric Epidemiology",
        "Psychological Medicine",
        "The Lancet Psychiatry",
        "Journal of Affective Disorders",
        "General Hospital Psychiatry",
        "Community Mental Health Journal",
        "American Journal of Orthopsychiatry",
        "Psychological Trauma",
    ),
    units_and_formulas_notes=(
        "量表得分报告原始分与标准化分；阳性界值须注明来源",
        "效应量用 Cohen's d；组内前后比较用配对 t 或 Wilcoxon",
        "随访周期用天/周/月并统一报告",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("Columbia-Suicide Severity Rating Scale C-SSRS", "Ask Suicide-Screening Questions ASQ", "SAD PERSONS Score", "Stanley-Brown Safety Planning Intervention", "Columbia Lighthouse Project", "SAFE-T Suicide Assessment", "Columbia Protocol", "SPARC App", "SafePlace App", "Moodpath", "Moodfit", "Sofia App", "Woebot", "Wysa", "Youper", "Dax", "QPRGate", "iTalk", "Crisis Text Line", "NAMI HelpLine", "988 Suicide and Crisis Lifeline", "SAMHSA Disaster Distress Helpline", "Mental Health First Aid", "MHA International", "Doxy.me", "Zoom", "SPSS", "Stata", "R", "JASP", "NVivo", "MAXQDA", "ATLAS.ti", "RedCap", "Qualtrics", "SurveyMonkey", "IBM SPSS Statistics"),
    category="医学",
    databases=("PubMed", "PsycINFO", "OpenAlex", "Crossref", "Suicide Statistics Database", "Lancet Psychiatry Archive"),
)
