"""草与牧场生产学科论文支持：放牧试验/饲草评价/草地退化与恢复/草地生态体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="crop_and_pasture_production",
    aliases=(
        "crop and pasture production",
        "草与牧场生产",
        "牧草与草地生产",
        "牧草生产",
        "pasture management",
        "rangeland science",
        "forage crops",
        "草地学",
        "放牧学",
        "grassland production",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "materials and methods",
            "results",
            "discussion",
            "conclusions",
            "references",
        ),
        "grazing_trial": (
            "abstract",
            "introduction",
            "site and grazing description（放牧制度）",
            "experimental design",
            "herbage and livestock measurements",
            "results",
            "discussion",
            "references",
        ),
        "forage_evaluation": (
            "abstract",
            "introduction",
            "materials",
            "sampling and analysis",
            "results",
            "digestibility and energy",
            "conclusions",
            "references",
        ),
        "restoration": (
            "abstract",
            "degradation assessment",
            "restoration measures",
            "monitoring",
            "results",
            "cost-benefit analysis",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope",
            "synthesis",
            "research gaps",
            "references",
        ),
    },
    citation_style="Elsevier numbered 或 ASA-CSSA-SSSA style",
    reporting_standards={
        "grazing": "放牧试验须报告畜种、载畜率、放牧制度（连续/轮牧/休牧）、放牧期与休止期",
        "herbage": "牧草产量测定方法（样方/剪取高度）与测定次数须给出",
        "quality": "饲草养分与消化能/粗蛋白按干物质基础报告",
        "degradation": "退化度分级标准须注明（轻度/中度/重度）",
        "climate": "试验季降水与积温须报告并说明来源",
        "rangeland_health": "草地健康评估须注明指标体系与权重",
    },
    conventions=(
        "草种/品种名用拉丁学名或正式品种名，首现注明",
        "牧草产量用 t/ha 或 kg DM/ha；消化能按 MJ/kg DM 报告",
        "载畜率用饲养单位（animal unit, AU）或存栏数并说明换算",
        "遥感指标（NDVI/EVI）须注明传感器与重访周期",
        "单位用 SI；显著性字母标注法全文一致",
    ),
    key_venues=(
        "Grass and Forage Science",
        "Journal of Animal Science",
        "Livestock Science",
        "Animal Production Science",
        "Soil Use and Management",
        "Journal of Applied Ecology",
        "Agricultural and Forest Meteorology",
        "Pasture and Forage Systems",
        "Grassland Ecology, Management and Conservation",
        "Rangelands",
        "Journal of Range Management",
        "Range Ecology Management",
        "Agriculture, Ecosystems & Environment",
        "Ecological Indicators",
    ),
    units_and_formulas_notes=(
        "牧草产量 kg DM/ha；饲喂价值用消化能 MJ/kg DM 或饲料单位报告",
        "载畜率用 animal unit (AU) 或 stock unit；换算系数须注明",
        "退化度以覆盖度、生产力、物种多样性的偏离度定量表达",
        "NDVI/EVI 须注明传感器型号与影像分辨率",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("FORANZ", "DAFMOS", "RuminC", "APEX", "CROPWATCH Forage Model", "PastureManger", "Grazeland", "Rangeland Planner", "Rangelis", "Herbalyzer", "Herbage Mass Measuring Cylinder", "ForageLAB", "Foss Analytical NIR", "Lactanalyzer", "Sentinel Hub", "Google Earth Engine", "ArcGIS", "ArcGIS Pro", "QGIS", "QGIS Processing", "ENVI", "ERDAS IMAGINE", "Sentinel-2", "Landsat 8/9", "MODIS", "Drone DJI Phantom", "Drone DJI Mavic", "NDVI Sensor GreenSeeker", "Delta-T Devices ThetaProbe", "Apogee PS-50", "SPAD-501", "Soiltek Soil Water", "ImageJ", "R", "SPSS", "Origin", "MATLAB", "Stata"),
    category="农学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "FAOSTAT", "USDA-ARS", "CGIAR", "Copernicus Sentinel", "GRASSET"),
)
