"""作物与畜牧生产学科论文支持：大田试验/畜群试验/营养评价/生产报告体裁、ASA-CSSA-SSSA 与畜牧注记。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="crop_and_livestock_production",
    aliases=(
        "crop and livestock production",
        "作物与畜牧生产",
        "作物与畜禽生产",
        "种植业与养殖业",
        "agronomy and animal production",
        "crop production",
        "livestock production",
        "畜牧生产",
        "农业综合生产",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "materials and methods（材料与方法）",
            "results",
            "discussion",
            "conclusions",
            "references",
        ),
        "field_trial": (
            "abstract",
            "introduction",
            "site description（土壤/气候/前茬）",
            "experimental design（随机区组/裂区）",
            "results",
            "yield and quality analysis",
            "references",
        ),
        "animal_trial": (
            "abstract",
            "introduction",
            "animals and management（饲养管理）",
            "diet composition（日粮组成）",
            "measurements",
            "results",
            "discussion",
            "references",
        ),
        "production_report": (
            "abstract",
            "farm description",
            "production records",
            "technical and economic analysis",
            "recommendations",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope",
            "synthesis",
            "research gaps",
            "references",
        ),
    },
    citation_style="ASA-CSSA-SSSA style 或 Elsevier numbered；畜牧可参照 ASAS 或 Elsevier",
    reporting_standards={
        "trial": "田间试验设计（随机区组/裂区）、重复数与小区面积须给出",
        "soil": "土壤类型、pH、有机质、前茬与基础肥力须报告",
        "climate": "试验季气象数据（降水/积温）须给出并注明来源",
        "yield": "产量按标准含水率折算；统计用 ANOVA+多重比较（LSD/Tukey）",
        "animal": "日粮配方、饲养密度、光照与试验周期须报告",
        "nutrient": "养分按 N-P2O5-K2O 折算；饲料分析按干物质基础",
        "animal_ethics": "动物试验须附伦理批准号",
    },
    conventions=(
        "品种/品系名给正式登记名；转基因材料注明转化事件与载体",
        "产量用 t/ha 或 kg/ha；养分按 N-P2O5-K2O 折算；单位用 SI",
        "畜禽生产按头/栏/日报告；体重按 kg；产奶/产蛋按 d 报告",
        "土壤与饲料分析须注明测定方法与仪器型号",
        "显著性字母标注法全文一致；效应量与多重比较方法须注明",
    ),
    key_venues=(
        "Crop Science",
        "Agronomy Journal",
        "Field Crops Research",
        "European Journal of Agronomy",
        "The Crop Journal",
        "Journal of Animal Science",
        "Journal of Dairy Science",
        "Livestock Science",
        "Animal Production Science",
        "Poultry Science",
        "British Journal of Nutrition",
        "Animal Feed Science and Technology",
        "Journal of Animal Physiology and Animal Nutrition",
    ),
    units_and_formulas_notes=(
        "产量 t/ha 或 kg/ha；养分利用率（NUE/PFP）公式须给出",
        "水分利用效率 WUE = 产量/蒸散量，单位 kg/m³",
        "增重与日粮用日增重（g/d）与料重比（FCR）报告",
        "公式用 amsmath；显示公式仅在被引用时编号",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("DSSAT", "APSIM", "AquaCrop", "STICS", "WOFOST", "CERES", "SimsGrow", "FarmSim", "CropScape", "The Climate Corporation FieldView", "FarmLogs", "Granular Intelligence", "Breedplan", "DHI", "BVDS", "DairyComp International", "HerdManager", "Lactanalyzer", "ForageLAB", "Foss Analytical NIR", "DAFMOS", "RuminC", "Sentinel Hub", "ArcGIS", "QGIS", "ENVI", "Drone DJI Agras T30", "Drone DJI Phantom", "Delta-T Devices ThetaProbe", "LI-COR LI-6400XT", "SPAD-501", "LAI Scanner LiCor", "ImageJ", "R", "SPSS", "Origin", "ASAS"),
    category="农学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "FAOSTAT", "USDA-ARS", "CGIAR", "Crop Trust", "DHI"),
)
