"""作物栽培与饲养学科论文支持：田间试验/栽培技术/灌溉水肥/病虫害防治/设施栽培体裁。"""

from __future__ import annotations

from sciforge.disciplines.base import Discipline

DISCIPLINE = Discipline(
    name="crop_growing_and_husbandry",
    aliases=(
        "crop growing and husbandry",
        "作物栽培与饲养",
        "作物栽培",
        "crop cultivation",
        "crop husbandry",
        "agronomy",
        "栽培学",
        "精准农业",
        "precision agriculture",
        "设施栽培",
        "设施农业",
    ),
    paper_types={
        "research": (
            "abstract",
            "introduction",
            "materials and methods（试验材料与方法）",
            "results",
            "discussion",
            "conclusions",
            "references",
        ),
        "field_trial": (
            "abstract",
            "introduction",
            "site description（立地条件）",
            "experimental design（随机区组/裂区/裂行）",
            "cultivation management（栽培措施）",
            "results",
            "yield and quality analysis",
            "references",
        ),
        "greenhouse_trial": (
            "abstract",
            "introduction",
            "facility description（设施环境参数）",
            "growing medium and fertigation",
            "results",
            "discussion",
            "references",
        ),
        "pest_disease_assessment": (
            "abstract",
            "introduction",
            "sampling design",
            "assessment method",
            "results",
            "management recommendations",
            "references",
        ),
        "review": (
            "abstract",
            "introduction",
            "scope",
            "synthesis",
            "research gaps",
            "references",
        ),
    },
    citation_style="ASA-CSSA-SSSA style 或 Elsevier numbered",
    reporting_standards={
        "trial": "田间试验设计（随机区组/裂区/裂行）、重复数与小区面积须给出",
        "soil": "土壤类型、pH、有机质、速效养分与前茬须报告",
        "cultivation": "播种密度、播期、施肥与灌溉制度须完整给出",
        "climate": "试验季气象数据（降水/积温/日照）须给出并注明来源",
        "yield": "产量按标准含水率折算；统计用 ANOVA+多重比较（LSD/Tukey）",
        "pest": "病虫害调查须注明调查方法、取样数与分级标准",
        "greenhouse": "设施环境（温/湿/光/CO2）须报告监测方式与周期",
    },
    conventions=(
        "品种/品系名给正式登记名；转基因材料注明转化事件与载体",
        "产量用 t/ha 或 kg/ha 并按标准含水率折算；水分测定方法须注明",
        "施肥量按 N-P2O5-K2O 计；灌溉量按 mm 或 m³/ha 报告",
        "农艺性状给测定方法（株高/穗长/SPAD/LAI/叶面积）与仪器型号",
        "单位用 SI（kg/ha、mm、°C、mol/m²·s）；显著性字母标注法全文一致",
    ),
    key_venues=(
        "Crop Science",
        "Agronomy Journal",
        "Field Crops Research",
        "European Journal of Agronomy",
        "Plant and Soil",
        "Agronomy",
        "Horticulture Research",
        "Scientia Horticulturae",
        "Journal of Applied Horticulture",
        "The Crop Journal",
        "Computers and Electronics in Agriculture",
        "Precision Agriculture",
        "Plant Methods",
        "Pest Management Science",
        "Crop Protection",
    ),
    units_and_formulas_notes=(
        "产量 t/ha 或 kg/ha；养分利用率（NUE/PFP）公式须给出",
        "水分利用效率 WUE = 产量/蒸散量，单位 kg/m³",
        "光能利用率 LUE = GPP/截获辐射，单位 g/MJ",
        "叶面积指数 LAI 用 m²/m²；气孔导度用 mol/m²·s",
        "公式用 amsmath；显示公式仅在被引用时编号",
    ),
    paper_capable=True,
    contribution_forms=("论文", "学术专著", "软件与代码", "专利", "教案与教材", "报告", "数据集"),
    tools=("DSSAT", "APSIM", "AquaCrop", "STICS", "WOFOST", "CERES", "SimsGrow", "CropScape", "The Climate Corporation FieldView", "John Deere Operations Center", "Trimble Ag Software", "AGCO CommandCenter", "CNH FieldOps One", "ISOBUS", "AgEagle", "PrecisionHawk", "Granular Intelligence", "Drone DJI Agras T30", "Drone DJI Phantom", "Drone DJI Matrice", "GreenSeeker NDVI", "Asabi FieldScan", "Sentinel Hub", "Google Earth Engine", "ArcGIS", "ArcGIS Pro", "QGIS", "ENVI", "PlantScreen", "WinCDBI", "Delta-T Devices ThetaProbe", "Soiltek Soil Water", "LI-COR LI-6400XT", "Apogee PS-50", "SPAD-501", "LAI Scanner LiCor", "Soiltek Soil Water Sensor", "SoilPen", "Fluke 56 pH Meter", "Mettler Toledo Karl Fischer Moisture Analyzer", "Trimble R12 GNSS", "Campbell Scientific", "Davis Vantage Pro2", "ImageJ", "R", "SPSS", "Origin", "MATLAB"),
    category="农学",
    databases=("OpenAlex", "Crossref", "CNKI", "万方", "FAOSTAT", "USDA-ARS", "CGIAR", "NASA POWER", "Crop Trust"),
)
