"""代码生成：复现脚本生成。

优先使用内部 LLM（若已配置）；否则回退到确定性模板生成（基于解析出的
超参数/数据形状），保证无外部依赖时也能跑通闭环。
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional


def _extract_hypers(parse: dict) -> dict:
    """从解析产物启发式抽取超参数（搜索常见键）。"""
    pages_text = "\n".join(parse.get("pages_text", []))
    hypers: dict = {}
    patterns = {
        "learning_rate": r"learning\s*rate[=:\s]+([0-9.eE\-]+)",
        "batch_size": r"batch\s*size[=:\s]+(\d+)",
        "epochs": r"epochs?[=:\s]+(\d+)",
        "hidden": r"hidden(?:\s*size)?[=:\s]+(\d+)",
        "seed": r"seed[=:\s]+(\d+)",
    }
    for key, pat in patterns.items():
        m = re.search(pat, pages_text, re.I)
        if m:
            try:
                hypers[key] = float(m.group(1)) if "." in m.group(1) else int(m.group(1))
            except ValueError:
                pass
    return hypers


def _numpy_template(hypers: dict, title: str) -> str:
    lr = float(hypers.get("learning_rate", 0.01))
    batch = int(hypers.get("batch_size", 32))
    epochs = int(hypers.get("epochs", 50))
    hidden = int(hypers.get("hidden", 16))
    seed = int(hypers.get("seed", 42))

    # 生成一个可复现的合成回归任务，训练单隐层网络，输出训练/验证 loss 曲线。
    # 注释保留论文标题，便于溯源。
    return f'''# Auto-generated by sci-forge (template fallback)
# Paper: {json.dumps(title, ensure_ascii=False)}

import numpy as np

rng = np.random.default_rng({seed})
N = 512
X = rng.standard_normal((N, 8))
true_w = rng.standard_normal(8)
y = X @ true_w + 0.1 * rng.standard_normal(N)

# train/test split (纯 numpy)
idx = rng.permutation(N)
split = int(N * 0.8)
Xtr, Xte = X[idx[:split]], X[idx[split:]]
ytr, yte = y[idx[:split]], y[idx[split:]]

W1 = rng.standard_normal((8, {hidden})) * 0.5
b1 = np.zeros(({hidden},))
W2 = rng.standard_normal(({hidden}, 1)) * 0.5
b2 = np.zeros((1, 1))

lr = {lr!r}
epochs = {epochs}

loss_history = []
for epoch in range(epochs):
    pidx = rng.permutation(len(Xtr))
    for start in range(0, len(Xtr), {batch}):
        bi = pidx[start:start+{batch}]
        xb = Xtr[bi]
        h = np.tanh(xb @ W1 + b1)
        pred = h @ W2 + b2
        err = pred - ytr[bi].reshape(-1,1)
        gW2 = h.T @ err
        gb2 = err.sum(axis=0, keepdims=True)
        gh = err @ W2.T * (1 - h**2)
        gW1 = xb.T @ gh
        gb1 = gh.sum(axis=0)
        W2 -= lr * gW2
        b2 -= lr * gb2
        W1 -= lr * gW1
        b1 -= lr * gb1

    h = np.tanh(Xtr @ W1 + b1)
    pred = h @ W2 + b2
    train_loss = float(np.mean((pred - ytr.reshape(-1,1))**2))
    loss_history.append(train_loss)
    set_metric('train_loss', train_loss, 'real')

h = np.tanh(Xte @ W1 + b1)
pred = h @ W2 + b2
test_loss = float(np.mean((pred - yte.reshape(-1,1))**2))
# r2_score (纯 numpy)
ss_res = float(np.sum((yte - pred.ravel())**2))
ss_tot = float(np.sum((yte - yte.mean())**2))
r2 = 1.0 - ss_res / ss_tot
set_metric('test_loss', test_loss, 'real')
set_metric('r2', r2, 'real')

import matplotlib.pyplot as plt
plt.figure(figsize=(5,4))
plt.plot(np.arange(1, len(loss_history)+1), loss_history)
plt.title('Training convergence')
plt.xlabel('epoch'); plt.ylabel('loss')
plt.savefig('convergence.png', dpi=120)
plt.close()
'''

def generate_code(parse: dict, plan: dict, framework: str = "pytorch",
                  llm_fn=None) -> tuple[str, dict]:
    """生成复现代码。

    Returns:
        (源代码, log)：log 记录生成方式（llm/template）与抽取的超参数。
    """
    hypers = _extract_hypers(parse)
    log = {"generator": "template", "hypers": hypers}
    title = parse.get("title", "") or ""
    # 若提供了 LLM 生成器且框架为 pytorch/tensorflow，尝试由 LLM 生成；
    # 失败时回退模板。
    if llm_fn is not None:
        try:
            src = llm_fn(hypers, parse, plan, framework)
            if src and "set_metric" in src:
                log["generator"] = "llm"
                return src, log
        except Exception as e:  # noqa: BLE001
            log["llm_error"] = str(e)
    # 回退模板
    return _numpy_template(hypers, title), log
